=== inab/benchmarking-data-model/json-schemas/1.0.x/challenge.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Challenge",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Challenge concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the challenge, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"pattern": "^(?!(?i)OEB).+$",
					"description": "Identifiers used on submission must not begin with OEB. Client tools must use always this pattern to validate",
					"writeOnly": true
				},
				{
					"pattern": "^OEBX[0-9]{3}t[A-Z0-9]{6}$",
					"description": "Temporary identifiers internally used must follow this pattern",
					"readOnly": true
				},
				{
					"pattern": "^OEBX[0-9]{3}[A-Z0-9]{7}$",
					"description": "Identifiers returned by the APIs must follow this pattern",
					"readOnly": true
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Challenge" ]
		},
		"orig_id": {
			"title": "The challenge original id",
			"description": "The field is filled in on server side, and it contains the original id used on data submission for this challenge, used by the community",
			"readOnly": true,
			"pattern": "^(?!(?i)OEB).+$",
			"type": "string",
			"minLength": 1
		},
		"name": {
			"title": "Short challenge name",
			"minLength": 1,
			"type": "string"
		},
		"acronym": {
			"title": "Friendly challenge acronym",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long description of the challenge",
			"type": "string"
		},
		"benchmarking_event_id": {
			"title": "The parent benchmarking event",
			"minLength": 1,
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "BenchmarkingEvent",
					"members": [ "." ]
				}
			]
		},
		"is_automated": {
			"title": "Is this an automated challenge?",
			"type": "boolean"
		},
		"dates": {
			"title": "Relevant dates for this challenge",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the challenge",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the challenge",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this challenge becomes public",
					"type": "string",
					"format": "date-time"
				},
				"challenge_start": {
					"title": "When starts the challenge?",
					"type": "string",
					"format": "date-time"
				},
				"challenge_stop": {
					"title": "When stops the challenge?",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation","modification"],
			"dependencies": {
				"challenge_start": ["challenge_stop"],
				"challenge_stop": ["challenge_start"]
			}
		},
		"url": {
			"title": "The public link to an specific challenge page",
			"type": "string",
			"format": "uri"
		},
		"metrics_categories": {
			"title": "The metrics category/es appliable to all or part of the participants of this challenge",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"category": {
						"title": "Metrics category",
						"minLength": 1,
						"type": "string",
						"enum": ["aggregation","assessment"]
					},
					"description": {
						"title": "Description of the metrics category",
						"type": "string"
					},
					"metrics": {
						"title": "The list of metrics in this category",
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "object",
							"properties": {
								"metrics_id": {
									"title": "The metrics id",
									"type": "string",
									"foreign_keys": [
										{
											"schema_id": "Metrics",
											"members": [ "." ]
										}
									]
								},
								"tool_id": {
									"title": "The optional tool id which computes this metric(s)",
									"type": "string",
									"foreign_keys": [
										{
											"schema_id": "Tool",
											"members": [ "." ]
										}
									]
								}
							},
							"required": [ "metrics_id" ]
						}
					}
				},
				"required": [
					"metrics",
					"category"
				]
			}
		},
		"challenge_contact_ids": {
			"title": "The challenge contact id(s)",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"references": {
			"title": "The challenge reference id(s) (if any)",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","name","benchmarking_event_id","is_automated","dates","challenge_contact_ids"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/Challenges/Challenge_UCEC_OEBX002t00000V.json
{
    "_id": "TCGA:2018-04-05_UCEC",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Challenge",
    "acronym": "UCEC",
    "benchmarking_event_id": "TCGA:2018-04-05",
    "challenge_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "dates": {
        "challenge_start": "2018-04-05T05:00:00Z",
        "challenge_stop": "2018-04-05T02:00:00Z",
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z"
    },
    "is_automated": false,
    "metrics_categories": [
        {
            "category": "assessment",
            "description": "metrics used to benchmark the performance of cancer genes predictors in Challenge Uterine Corpus Endometrial Carcinoma, generating the assessment datatseta",
            "metrics": [
                {
                    "metrics_id": "TCGA:TPR",
                    "tool_id": "TCGA:compute_TPR"
                },
                {
                    "metrics_id": "TCGA:precision",
                    "tool_id": "TCGA:compute_precision"
                }
            ]
        },
        {
            "category": "aggregation",
            "description": "metrics used to aggregate the assessment data of all cancer genes predictors participating in challenge Uterine Corpus Endometrial Carcinoma in a consolidated Aggregation dataset",
            "metrics": [
                {
                    "metrics_id": "TCGA:aggregation",
                    "tool_id": "TCGA:aggregate_benchmark"
                }
            ]
        }
    ],
    "name": "Cancer Driver Genes Prediction Benchmark in Uterine Corpus Endometrial Carcinoma",
    "references": [
        "doi:10.1016/j.cell.2018.02.060"
    ],
    "url": "https://www.cancer.gov/about-nci/organization/ccg/research/structural-genomics/tcga/studied-cancers/uterine"
}
