=== inab/benchmarking-data-model/json-schemas/1.0.x/dataset.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Dataset concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the dataset, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"pattern": "^OEBD[0-9]{3}t[A-Z0-9]{6}$",
					"description": "Temporary identifiers internally used must follow this pattern",
					"readOnly": true
				},
				{
					"pattern": "^OEBD[0-9]{3}[A-Z0-9]{7}$",
					"description": "Identifiers returned by the APIs must follow this pattern",
					"readOnly": true
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset" ]
		},
		"_metadata": {
			"$ref": "_shared#/definitions/Metadata"
		},
		"orig_id": {
			"title": "The dataset original id",
			"$ref": "_shared#/definitions/OriginalId"
		},
		"community_ids": {
			"title": "The communities where this dataset was generated or used",
			"description": "This field is redundant, as it can be obtained from the challenges",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				]
			}
		},
		"challenge_ids": {
			"title": "The challenge(s) where this dataset was generated or used",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Challenge",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"visibility": {
			"title": "The visibility of this dataset, which must be acknowledged by the APIs",
			"type": "string",
			"enum": [ "public", "community", "challenge", "participant" ]
		},
		"name": {
			"title": "Short dataset name",
			"minLength": 1,
			"type": "string"
		},
		"version": {
			"title": "Version (or relelase date) of the dataset",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long dataset description",
			"type": "string"
		},
		"dates": {
			"title": "Relevant dates for this dataset",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this dataset becomes public",
					"type": "string",
					"format": "date-time"
				}
			},
			"additionalProperties": false,
			"required": ["creation","modification"]
		},
		"type": {
			"title": "Type of dataset. Aggregation datasets are combinations of other aggregations or assessments.",
			"type": "string",
			"mingLength": 1,
			"enum": [ "public_reference", "metrics_reference", "input", "participant", "assessment", "aggregation", "other" ]
		},
		"datalink": {
			"title": "The data itself, either linked or embedded",
			"type": "object",
			"oneOf": [
				{
					"title": "Inline, embedded data",
					"properties": {
						"inline_data": {
							"title": "Inline data in JSON format",
							"type": "object",
							"minProperties": 1,
							"additionalProperties": true
						},
						"schema_url": {
							"title": "The optional URL to the JSON Schema which validates the inline data. It could be embedded, using the data: protocol encoding",
							"type": "string",
							"format": "uri"
						}
					},
					"additionalProperties": false,
					"required": [ "inline_data" ]
				},
				{
					"title": "The link to reach the dataset",
					"properties": {
						"uri": {
							"title": "Either inline, encoded data URI; or an official CURIE; or download link to the dataset itself; or a link to a Metalink describing the dataset; or a link to a MD5/SHA1 sums file with relative paths",
							"type": "string",
							"format": "uri"
						},
						"schema_uri": {
							"title": "The optional URI to the JSON Schema which validates the remote data, in case it is either JSON or YAML",
							"type": "string",
							"format": "uri"
						},
						"attrs": {
							"title": "Attributes describing the datalink: whether it is inline (i.e. a data URI); a CURIE; whether it is compressed, or an archive (tar, zip, rar), a metalink (RFC 5854, RFC 6249, https://en.wikipedia.org/wiki/Metalink) or a standard sums (MD5, SHA1) file",
							"type": "array",
							"minItems": 1,
							"uniqueItems": true,
							"anyOf": [
								{
									"items": {
										"type": "string",
										"enum": [ "inline","compressed", "archive", "metalink", "sums" ]
									}
								},
								{
									"items": {
										"type": "string",
										"enum": [ "curie", "compressed", "archive", "metalink" ]
									}
								}
							]
						},
						"validation_date": {
							"title": "Last validation date of the datalink",
							"type": "string",
							"format": "date-time"
						},
						"status": {
							"title": "Last validation status (unreachable content, missing content(404), interrupted while validating, corrupted (checksums, not all the contents available, etc...), ok) or the HTTP code (numerical)",
							"oneOf": [
								{
									"type": "string",
									"enum": [ "unreachable", "missing", "interrupted", "corrupted", "ok" ]
								},
								{
									"type": "integer",
									"minimum": 100,
									"exclusiveMaximum": 600
								}
							]
						}
					},
					"additionalProperties": false,
					"required": [ "uri", "attrs" ]
				}
			]
		},
		"dataset_contact_ids": {
			"title": "The contact id(s) of the depositor(s)/creator(s) of this dataset",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"depends_on": {
			"title": "The causal, direct dependencies of this dataset on a tool and other datasets, if available",
			"type": "object",
			"properties": {
				"metrics_id": {
					"title": "The id of the metrics tied to the tool id",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Metrics",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"tool_id": {
					"title": "The id of the tool which generated this dataset",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Tool",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"rel_dataset_ids": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"dataset_id": {
								"title": "The id of a dataset which was used to generate this new dataset",
								"type": "string",
								"foreign_keys": [
									{
										"schema_id": "Dataset",
										"members": [ "." ]
									}
								],
								"minLength": 1
							},
							"role": {
								"title": "The role of the referenced dataset generating the current one (used to generate the current dataset, superseded by the generated dataset, ....)",
								"type": "string",
								"enum": [ "dependency", "superseded", "report" ],
								"default": "dependency"
							}
						},
						"additionalProperties": false,
						"required": [ "dataset_id" ]
					}
				}
			},
			"additionalProperties": false,
			"required": [ "rel_dataset_ids" ]
		},
		"references": {
			"title": "The reference id(s) of this dataset (if any)",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","challenge_ids","visibility","name","version","type","dates","datalink","dataset_contact_ids"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/participant_datasets/Dataset_participant_UCS_e-Driver_OEBD002t000072.json
{
    "_id": "TCGA:2018-04-05_UCS_P_e-Driver",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "TCGA:2018-04-05_UCS"
    ],
    "community_ids": [
        "OEBC001"
    ],
    "datalink": {
        "attrs": [
            "archive"
        ],
        "status": "ok",
        "uri": "https://api.gdc.cancer.gov/data/5bd22660-40a1-42ac-a791-0a8c5ef8f978",
        "validation_date": "2018-04-05T00:00:00Z"
    },
    "dataset_contact_ids": [
        "Eduard.Porta"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z"
    },
    "depends_on": {
        "rel_dataset_ids": [
            {
                "dataset_id": "TCGA:2018-04-05_input"
            }
        ],
        "tool_id": "TCGA:e-Driver"
    },
    "description": "List of Cancer Driver Genes predicted by tool e-Driver in Uterine Carcinosarcoma",
    "name": "Cancer Driver Genes in Uterine Carcinosarcoma",
    "type": "participant",
    "version": "unknown",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/assessment_datasets/Dataset_assessment_ALL_2020plus_TPR_OEBD002t0000NK.json
{
    "_id": "TCGA:2018-04-05_ALL_A_TPR_2020plus",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "TCGA:2018-04-05_ALL"
    ],
    "community_ids": [
        "OEBC001"
    ],
    "datalink": {
        "inline_data": {
            "value": 0.6254180602006689
        }
    },
    "dataset_contact_ids": [
        "Collin.Tokheim"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "TCGA:TPR",
        "rel_dataset_ids": [
            {
                "dataset_id": "TCGA:2018-04-05_ALL_P_2020plus"
            },
            {
                "dataset_id": "TCGA:2018-04-05_ALL_M"
            }
        ],
        "tool_id": "TCGA:2020plus"
    },
    "description": "Assessment dataset for applying Metric 'True Positive Rate' to 2020plus predictions in All cancer types",
    "name": "Assesment of Metric TPR in 2020plus",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_G_STD_LUCA_SonicParanoid_STD_incorrect_trees.json
{
    "_id": "QfO:2011-07-07_G_STD_LUCA_A_STD_incorrect_trees_SonicParanoid",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_G_STD_LUCA"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.014775",
            "value": "0.217667"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:STD_incorrect_trees",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_SonicParanoid"
            },
            {
                "dataset_id": "QfO:2011-07-07_G_STD_LUCA_M"
            }
        ],
        "tool_id": "QfO:SonicParanoid"
    },
    "description": "Assessment dataset for applying Metric 'STD_incorrect_trees' to SonicParanoid predictions in Generalized Species Tree Discordance in LUCA",
    "name": "Assesment of STD_incorrect_trees in SonicParanoid",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_GOtest_SonicParanoid_sensitive_GOTest_schlicker.json
{
    "_id": "QfO:2011-07-07_GOtest_A_GOTest_schlicker_SonicParanoid_sensitive",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_GOtest"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.001287",
            "value": "0.483616"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:GOTest_schlicker",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_SonicParanoid_sensitive"
            },
            {
                "dataset_id": "QfO:2011-07-07_GOtest_M"
            }
        ],
        "tool_id": "QfO:SonicParanoid_sensitive"
    },
    "description": "Assessment dataset for applying Metric 'GOTest_schlicker' to SonicParanoid_sensitive predictions in Gene Ontology Conservation Test",
    "name": "Assesment of GOTest_schlicker in SonicParanoid_sensitive",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_G_STD_Fungi_OrthoFinder-2.0-BLAST_STD_comp_trees.json
{
    "_id": "QfO:2011-07-07_G_STD_Fungi_A_STD_comp_trees_OrthoFinder-2.0-BLAST",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_G_STD_Fungi"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": 0,
            "value": 20207.0
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:STD_comp_trees",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_OrthoFinder-2.0-BLAST"
            },
            {
                "dataset_id": "QfO:2011-07-07_G_STD_Fungi_M"
            }
        ],
        "tool_id": "QfO:OrthoFinder-2.0-BLAST"
    },
    "description": "Assessment dataset for applying Metric 'STD_comp_trees' to OrthoFinder-2.0-BLAST predictions in Generalized Species Tree Discordance in Fungi",
    "name": "Assesment of STD_comp_trees in OrthoFinder-2.0-BLAST",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_GOtest_OMA-GETHOGs_GOTest_schlicker.json
{
    "_id": "QfO:2011-07-07_GOtest_A_GOTest_schlicker_OMA-GETHOGs",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_GOtest"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.001247",
            "value": "0.481484"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:GOTest_schlicker",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_OMA-GETHOGs"
            },
            {
                "dataset_id": "QfO:2011-07-07_GOtest_M"
            }
        ],
        "tool_id": "QfO:OMA-GETHOGs"
    },
    "description": "Assessment dataset for applying Metric 'GOTest_schlicker' to OMA-GETHOGs predictions in Gene Ontology Conservation Test",
    "name": "Assesment of GOTest_schlicker in OMA-GETHOGs",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_G_STD_Fungi_OMA-Pairs-2.0_STD_incorrect_trees.json
{
    "_id": "QfO:2011-07-07_G_STD_Fungi_A_STD_incorrect_trees_OMA-Pairs-2.0",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_G_STD_Fungi"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.008678",
            "value": "0.062667"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:STD_incorrect_trees",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_OMA-Pairs-2.0"
            },
            {
                "dataset_id": "QfO:2011-07-07_G_STD_Fungi_M"
            }
        ],
        "tool_id": "QfO:OMA-Pairs-2.0"
    },
    "description": "Assessment dataset for applying Metric 'STD_incorrect_trees' to OMA-Pairs-2.0 predictions in Generalized Species Tree Discordance in Fungi",
    "name": "Assesment of STD_incorrect_trees in OMA-Pairs-2.0",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_G_STD_Eukaryota_SonicParanoid_fast_STD_comp_trees.json
{
    "_id": "QfO:2011-07-07_G_STD_Eukaryota_A_STD_comp_trees_SonicParanoid_fast",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_G_STD_Eukaryota"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": 0,
            "value": 3155.0
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:STD_comp_trees",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_SonicParanoid_fast"
            },
            {
                "dataset_id": "QfO:2011-07-07_G_STD_Eukaryota_M"
            }
        ],
        "tool_id": "QfO:SonicParanoid_fast"
    },
    "description": "Assessment dataset for applying Metric 'STD_comp_trees' to SonicParanoid_fast predictions in Generalized Species Tree Discordance in Eukaryota",
    "name": "Assesment of STD_comp_trees in SonicParanoid_fast",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}
