=== inab/benchmarking-data-model/json-schemas/1.0.x/dataset.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Dataset concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the dataset, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"pattern": "^OEBD[0-9]{3}t[A-Z0-9]{6}$",
					"description": "Temporary identifiers internally used must follow this pattern",
					"readOnly": true
				},
				{
					"pattern": "^OEBD[0-9]{3}[A-Z0-9]{7}$",
					"description": "Identifiers returned by the APIs must follow this pattern",
					"readOnly": true
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset" ]
		},
		"_metadata": {
			"$ref": "_shared#/definitions/Metadata"
		},
		"orig_id": {
			"title": "The dataset original id",
			"$ref": "_shared#/definitions/OriginalId"
		},
		"community_ids": {
			"title": "The communities where this dataset was generated or used",
			"description": "This field is redundant, as it can be obtained from the challenges",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				]
			}
		},
		"challenge_ids": {
			"title": "The challenge(s) where this dataset was generated or used",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Challenge",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"visibility": {
			"title": "The visibility of this dataset, which must be acknowledged by the APIs",
			"type": "string",
			"enum": [ "public", "community", "challenge", "participant" ]
		},
		"name": {
			"title": "Short dataset name",
			"minLength": 1,
			"type": "string"
		},
		"version": {
			"title": "Version (or relelase date) of the dataset",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long dataset description",
			"type": "string"
		},
		"dates": {
			"title": "Relevant dates for this dataset",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this dataset becomes public",
					"type": "string",
					"format": "date-time"
				}
			},
			"additionalProperties": false,
			"required": ["creation","modification"]
		},
		"type": {
			"title": "Type of dataset. Aggregation datasets are combinations of other aggregations or assessments.",
			"type": "string",
			"mingLength": 1,
			"enum": [ "public_reference", "metrics_reference", "input", "participant", "assessment", "aggregation", "other" ]
		},
		"datalink": {
			"title": "The data itself, either linked or embedded",
			"type": "object",
			"oneOf": [
				{
					"title": "Inline, embedded data",
					"properties": {
						"inline_data": {
							"title": "Inline data in JSON format",
							"type": "object",
							"minProperties": 1,
							"additionalProperties": true
						},
						"schema_url": {
							"title": "The optional URL to the JSON Schema which validates the inline data. It could be embedded, using the data: protocol encoding",
							"type": "string",
							"format": "uri"
						}
					},
					"additionalProperties": false,
					"required": [ "inline_data" ]
				},
				{
					"title": "The link to reach the dataset",
					"properties": {
						"uri": {
							"title": "Either inline, encoded data URI; or an official CURIE; or download link to the dataset itself; or a link to a Metalink describing the dataset; or a link to a MD5/SHA1 sums file with relative paths",
							"type": "string",
							"format": "uri"
						},
						"schema_uri": {
							"title": "The optional URI to the JSON Schema which validates the remote data, in case it is either JSON or YAML",
							"type": "string",
							"format": "uri"
						},
						"attrs": {
							"title": "Attributes describing the datalink: whether it is inline (i.e. a data URI); a CURIE; whether it is compressed, or an archive (tar, zip, rar), a metalink (RFC 5854, RFC 6249, https://en.wikipedia.org/wiki/Metalink) or a standard sums (MD5, SHA1) file",
							"type": "array",
							"minItems": 1,
							"uniqueItems": true,
							"anyOf": [
								{
									"items": {
										"type": "string",
										"enum": [ "inline","compressed", "archive", "metalink", "sums" ]
									}
								},
								{
									"items": {
										"type": "string",
										"enum": [ "curie", "compressed", "archive", "metalink" ]
									}
								}
							]
						},
						"validation_date": {
							"title": "Last validation date of the datalink",
							"type": "string",
							"format": "date-time"
						},
						"status": {
							"title": "Last validation status (unreachable content, missing content(404), interrupted while validating, corrupted (checksums, not all the contents available, etc...), ok) or the HTTP code (numerical)",
							"oneOf": [
								{
									"type": "string",
									"enum": [ "unreachable", "missing", "interrupted", "corrupted", "ok" ]
								},
								{
									"type": "integer",
									"minimum": 100,
									"exclusiveMaximum": 600
								}
							]
						}
					},
					"additionalProperties": false,
					"required": [ "uri", "attrs" ]
				}
			]
		},
		"dataset_contact_ids": {
			"title": "The contact id(s) of the depositor(s)/creator(s) of this dataset",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"depends_on": {
			"title": "The causal, direct dependencies of this dataset on a tool and other datasets, if available",
			"type": "object",
			"properties": {
				"metrics_id": {
					"title": "The id of the metrics tied to the tool id",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Metrics",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"tool_id": {
					"title": "The id of the tool which generated this dataset",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Tool",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"rel_dataset_ids": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"dataset_id": {
								"title": "The id of a dataset which was used to generate this new dataset",
								"type": "string",
								"foreign_keys": [
									{
										"schema_id": "Dataset",
										"members": [ "." ]
									}
								],
								"minLength": 1
							},
							"role": {
								"title": "The role of the referenced dataset generating the current one (used to generate the current dataset, superseded by the generated dataset, ....)",
								"type": "string",
								"enum": [ "dependency", "superseded", "report" ],
								"default": "dependency"
							}
						},
						"additionalProperties": false,
						"required": [ "dataset_id" ]
					}
				}
			},
			"additionalProperties": false,
			"required": [ "rel_dataset_ids" ]
		},
		"references": {
			"title": "The reference id(s) of this dataset (if any)",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","challenge_ids","visibility","name","version","type","dates","datalink","dataset_contact_ids"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_SwissTree_InParanoidCore_SwissTree_TPR.json
{
    "_id": "QfO:2011-07-07_SwissTree_A_SwissTree_TPR_InParanoidCore",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_SwissTree"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.065164",
            "value": "0.884322"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:SwissTree_TPR",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_InParanoidCore"
            },
            {
                "dataset_id": "QfO:2011-07-07_SwissTree_M"
            }
        ],
        "tool_id": "QfO:InParanoidCore"
    },
    "description": "Assessment dataset for applying Metric 'SwissTree_TPR' to InParanoidCore predictions in Agreement with Reference Gene Phylogenies: SwissTree",
    "name": "Assesment of SwissTree_TPR in InParanoidCore",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_G_STD_LUCA_EggNOG_STD_num_orthologs.json
{
    "_id": "QfO:2011-07-07_G_STD_LUCA_A_STD_num_orthologs_EggNOG",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_G_STD_LUCA"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": 0,
            "value": 4572074.0
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:STD_num_orthologs",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_EggNOG"
            },
            {
                "dataset_id": "QfO:2011-07-07_G_STD_LUCA_M"
            }
        ],
        "tool_id": "QfO:EggNOG"
    },
    "description": "Assessment dataset for applying Metric 'STD_num_orthologs' to EggNOG predictions in Generalized Species Tree Discordance in LUCA",
    "name": "Assesment of STD_num_orthologs in EggNOG",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/CAMEO/Datasets/participant/2017-01-14_00000003_1_P_server20.json
{
  "_id": "CAMEO:2017-01-14_00000003_1_P_server20",
  "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
  "type": "participant",
  "challenge_ids": ["CAMEO:CAMEO-3D_2017-01-14"],
  "name": "Solution structure of a PWWP doamin from Trypanosoma brucei",
  "description": "Target 04_1 of week 2017-01-14. Server20",
  "version": "1",
  "visibility": "public",
  "datalink": {
    "uri": "https://www.cameo3d.org/static/data/modeling/2017.01.14/5EJJ_B/servers/server11/model-1/model-1.pdb",
    "attrs": ["inline"]
  },
  "dates": {
    "creation": "2017-01-14T00:00:00Z",
    "modification": "2017-01-18T00:00:00Z"
  },
  "depends_on": {
    "tool_id": "CAMEO:server20",
    "rel_dataset_ids": [
      {
        "dataset_id": "CAMEO:2017-01-14_00000004_1_I",
        "role": "dependency"
      }
    ]
  },
  "dataset_contact_ids": [
    "help.CAMEO-3D"
  ]
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_GOtest_OMA-Groups-2.0_GOTest_schlicker.json
{
    "_id": "QfO:2011-07-07_GOtest_A_GOTest_schlicker_OMA-Groups-2.0",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_GOtest"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.002065",
            "value": "0.515602"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:GOTest_schlicker",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_OMA-Groups-2.0"
            },
            {
                "dataset_id": "QfO:2011-07-07_GOtest_M"
            }
        ],
        "tool_id": "QfO:OMA-Groups-2.0"
    },
    "description": "Assessment dataset for applying Metric 'GOTest_schlicker' to OMA-Groups-2.0 predictions in Gene Ontology Conservation Test",
    "name": "Assesment of GOTest_schlicker in OMA-Groups-2.0",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_SwissTree_PhylomeDB_SwissTree_TPR.json
{
    "_id": "QfO:2011-07-07_SwissTree_A_SwissTree_TPR_PhylomeDB",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_SwissTree"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.064558",
            "value": "0.891767"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:SwissTree_TPR",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_PhylomeDB"
            },
            {
                "dataset_id": "QfO:2011-07-07_SwissTree_M"
            }
        ],
        "tool_id": "QfO:PhylomeDB"
    },
    "description": "Assessment dataset for applying Metric 'SwissTree_TPR' to PhylomeDB predictions in Agreement with Reference Gene Phylogenies: SwissTree",
    "name": "Assesment of SwissTree_TPR in PhylomeDB",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/assessment_datasets/Dataset_assessment_CHOL_MuSiC_precision_OEBD002t0000AZ.json
{
    "_id": "TCGA:2018-04-05_CHOL_A_precision_MuSiC",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "TCGA:2018-04-05_CHOL"
    ],
    "community_ids": [
        "OEBC001"
    ],
    "datalink": {
        "inline_data": {
            "value": 1.0
        }
    },
    "dataset_contact_ids": [
        "Nathan.Dees"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "TCGA:precision",
        "rel_dataset_ids": [
            {
                "dataset_id": "TCGA:2018-04-05_CHOL_P_MuSiC"
            },
            {
                "dataset_id": "TCGA:2018-04-05_CHOL_M"
            }
        ],
        "tool_id": "TCGA:MuSiC"
    },
    "description": "Assessment dataset for applying Metric 'Positive Predictive Value' to MuSiC predictions in Cholangiocarcinoma",
    "name": "Assesment of Metric precision-PPV in MuSiC",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/participant_datasets/Dataset_participant_EnsemblCompara-e56.json
{
    "_id": "QfO:2011-07-07_P_EnsemblCompara-e56",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_SwissTree",
        "QfO:2011-07-07_STD_Fungi",
        "QfO:2011-07-07_STD_Eukaryota",
        "QfO:2011-07-07_GOtest",
        "QfO:2011-07-07_TreeFam-A",
        "QfO:2011-07-07_G_STD_Fungi",
        "QfO:2011-07-07_G_STD_Eukaryota",
        "QfO:2011-07-07_G_STD_LUCA",
        "QfO:2011-07-07_G_STD_Vertebrata",
        "QfO:2011-07-07_ECtest"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "attrs": [
            "archive"
        ],
        "status": "ok",
        "uri": "https://orthology.benchmarkservice.org/raw/Ensembl_compara_v2-.929.rels.raw.gz",
        "validation_date": "2011-07-07T00:00:00Z"
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_I"
            }
        ],
        "tool_id": "QfO:EnsemblCompara-e56"
    },
    "description": "List of orthologs pairs predicted by EnsemblCompara-e56 using the Quest for Orthologs reference proteome",
    "name": "Orthologs predicted by EnsemblCompara-e56",
    "type": "participant",
    "version": "unknown",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/assessment_datasets/Dataset_assessment_SwissTree_OMA-Pairs-2.0_SwissTree_PPV.json
{
    "_id": "QfO:2011-07-07_SwissTree_A_SwissTree_PPV_OMA-Pairs-2.0",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_SwissTree"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": "0.065710",
            "value": "0.652428"
        }
    },
    "dataset_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:SwissTree_PPV",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_OMA-Pairs-2.0"
            },
            {
                "dataset_id": "QfO:2011-07-07_SwissTree_M"
            }
        ],
        "tool_id": "QfO:OMA-Pairs-2.0"
    },
    "description": "Assessment dataset for applying Metric 'SwissTree_PPV' to OMA-Pairs-2.0 predictions in Agreement with Reference Gene Phylogenies: SwissTree",
    "name": "Assesment of SwissTree_PPV in OMA-Pairs-2.0",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}
