=== inab/benchmarking-data-model/json-schemas/1.0.x/testAction.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Test Action concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the test action, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"pattern": "^OEBA[0-9]{3}t[A-Z0-9]{6}$",
					"description": "Temporary identifiers internally used must follow this pattern",
					"readOnly": true
				},
				{
					"pattern": "^OEBA[0-9]{3}[A-Z0-9]{7}$",
					"description": "Identifiers returned by the APIs must follow this pattern",
					"readOnly": true
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction" ]
		},
		"_metadata": {
			"$ref": "_shared#/definitions/Metadata"
		},
		"orig_id": {
			"title": "The test action original id",
			"$ref": "_shared#/definitions/OriginalId"
		},
		"tool_id": {
			"title": "The id of the processing tool",
			"description": "The id of the tool which processes a set of datasets for this action. Most of the time is a participant's tool, but in the case of aggregation or statistic events, is a tool related to a kind of challenge's metrics",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Tool",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"action_type": {
			"title": "The type of action",
			"description": "The type of action performed by the tool, also describing the kind of input datasets.\nTest Event = Input + Tool -> Participant Data\nMetrics event = Participant Data + Metrics -> Assessment Data\nStatistics event = Assessment Data + Metrics -> Challenge Data\n",
			"type": "string",
			"enum": [ "SetupEvent", "MetricsEvent", "StatisticsEvent", "AggregationEvent", "TestEvent" ]
		},
		"involved_datasets": {
			"title": "The incoming, outgoing and settings datasets involved in this test action",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"dataset_id": {
						"title": "A received dataset, with this id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Dataset",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"role": {
						"title": "The kind of dataset received for this action (report, metrics_reference, etc...)",
						"type": "string",
						"enum": [
							"incoming",
							"outgoing",
							"settings",
							"unknown"
						]
					},
					"received": {
						"title": "Reception date of the dataset (redundant, as the output dataset already has this date)",
						"type": "string",
						"format": "date-time"
					}
				},
				"required": [ "dataset_id", "role" ]
			}
		},
		"challenge_id": {
			"title": "The id of the challenge where this test action was generated",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Challenge",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"test_contact_ids": {
			"title": "Contact id(s) related to the action",
			"description": "The test action contact id(s), i.e. the runners of the tool and depositors of the results",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"status": {
			"title": "The lifecicle of the testAction will be managed by the API, validating it is progressing forward instead of backward",
			"type": "string",
			"enum": [ "scheduled", "sent", "incomplete", "complete", "failed" ]
		},
		"dates": {
			"title": "Relevant dates for this test action",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this test action becomes public",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation"]
		},
		"metadata": {
			"title": "Relevant metadata used to call the tool",
			"type": "object",
			"minProperties": 1,
			"additionalProperties": true
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","involved_datasets","challenge_id","test_contact_ids","dates"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/MetricsEvents/MetricsEvent_KIRC_ActiveDriver_precision_OEBA002t0000CY.json
{
    "_id": "OEBA002t0000CY",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "OEBX002t00000C",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t000084",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t00002L",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000DX",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_KIRC_metricsEvent_ActiveDriver_precision",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000002"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/metrics_events/MetricsEvent_SwissTree_SonicParanoid_sensitive_SwissTree_TPR.json
{
    "_id": "QfO:2011-07-07_SwissTree_metricsEvent_SonicParanoid_sensitive_SwissTree_TPR",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "QfO:2011-07-07_SwissTree",
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "reception": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_SwissTree_M",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_P_SonicParanoid_sensitive",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_SwissTree_A_SwissTree_TPR_SonicParanoid_sensitive",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "tool_id": "QfO:SonicParanoid_sensitive"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/test_events/TestEvent_GOtest_RBH-BBH.json
{
    "_id": "QfO:2011-07-07_testEvent_GOtest_RBH-BBH",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "TestEvent",
    "challenge_id": "QfO:2011-07-07_GOtest",
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "reception": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_I",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_P_RBH-BBH",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "tool_id": "QfO:RBH-BBH"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_SKCM_OncodriveFM_OEBA002t0000T8.json
{
    "_id": "OEBA002t0000T8",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000R",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000KI",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000KJ",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000U7",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_SKCM_OncodriveFM_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000008"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/metrics_events/MetricsEvent_HNSC_2020plus_precision_OEBA002t0000BY.json
{
    "_id": "TCGA:2018-04-05_HNSC_metricsEvent_2020plus_precision",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "TCGA:2018-04-05_HNSC",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "TCGA:2018-04-05_HNSC_M",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_HNSC_P_2020plus",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_HNSC_A_precision_2020plus",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "TCGA:2020plus"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/test_events/TestEvent_STD_Eukaryota_OrthoFinder-2.0-BLAST.json
{
    "_id": "QfO:2011-07-07_testEvent_STD_Eukaryota_OrthoFinder-2.0-BLAST",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "TestEvent",
    "challenge_id": "QfO:2011-07-07_STD_Eukaryota",
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "reception": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_I",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_P_OrthoFinder-2.0-BLAST",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "tool_id": "QfO:OrthoFinder-2.0-BLAST"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/MetricsEvents/MetricsEvent_UCEC_compositeDriver_TPR_OEBA002t0000LN.json
{
    "_id": "OEBA002t0000LN",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "OEBX002t00000W",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t00008O",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t00006Y",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000MM",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_UCEC_metricsEvent_compositeDriver_TPR",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000003"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_LGG_ActiveDriver_OEBA002t0000QL.json
{
    "_id": "OEBA002t0000QL",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000F",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000F8",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000F9",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000RK",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_LGG_ActiveDriver_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000002"
}
