=== inab/benchmarking-data-model/json-schemas/1.0.x/testAction.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Test Action concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the test action, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"pattern": "^OEBA[0-9]{3}t[A-Z0-9]{6}$",
					"description": "Temporary identifiers internally used must follow this pattern",
					"readOnly": true
				},
				{
					"pattern": "^OEBA[0-9]{3}[A-Z0-9]{7}$",
					"description": "Identifiers returned by the APIs must follow this pattern",
					"readOnly": true
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction" ]
		},
		"_metadata": {
			"$ref": "_shared#/definitions/Metadata"
		},
		"orig_id": {
			"title": "The test action original id",
			"$ref": "_shared#/definitions/OriginalId"
		},
		"tool_id": {
			"title": "The id of the processing tool",
			"description": "The id of the tool which processes a set of datasets for this action. Most of the time is a participant's tool, but in the case of aggregation or statistic events, is a tool related to a kind of challenge's metrics",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Tool",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"action_type": {
			"title": "The type of action",
			"description": "The type of action performed by the tool, also describing the kind of input datasets.\nTest Event = Input + Tool -> Participant Data\nMetrics event = Participant Data + Metrics -> Assessment Data\nStatistics event = Assessment Data + Metrics -> Challenge Data\n",
			"type": "string",
			"enum": [ "SetupEvent", "MetricsEvent", "StatisticsEvent", "AggregationEvent", "TestEvent" ]
		},
		"involved_datasets": {
			"title": "The incoming, outgoing and settings datasets involved in this test action",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"dataset_id": {
						"title": "A received dataset, with this id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Dataset",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"role": {
						"title": "The kind of dataset received for this action (report, metrics_reference, etc...)",
						"type": "string",
						"enum": [
							"incoming",
							"outgoing",
							"settings",
							"unknown"
						]
					},
					"received": {
						"title": "Reception date of the dataset (redundant, as the output dataset already has this date)",
						"type": "string",
						"format": "date-time"
					}
				},
				"required": [ "dataset_id", "role" ]
			}
		},
		"challenge_id": {
			"title": "The id of the challenge where this test action was generated",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Challenge",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"test_contact_ids": {
			"title": "Contact id(s) related to the action",
			"description": "The test action contact id(s), i.e. the runners of the tool and depositors of the results",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"status": {
			"title": "The lifecicle of the testAction will be managed by the API, validating it is progressing forward instead of backward",
			"type": "string",
			"enum": [ "scheduled", "sent", "incomplete", "complete", "failed" ]
		},
		"dates": {
			"title": "Relevant dates for this test action",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this test action becomes public",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation"]
		},
		"metadata": {
			"title": "Relevant metadata used to call the tool",
			"type": "object",
			"minProperties": 1,
			"additionalProperties": true
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","involved_datasets","challenge_id","test_contact_ids","dates"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/metrics_events/MetricsEvent_STD_Eukaryota_GETHOGs-2.0_STD_num_orthologs.json
{
    "_id": "QfO:2011-07-07_STD_Eukaryota_metricsEvent_GETHOGs-2.0_STD_num_orthologs",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "QfO:2011-07-07_STD_Eukaryota",
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "reception": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_STD_Eukaryota_M",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_P_GETHOGs-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_STD_Eukaryota_A_STD_num_orthologs_GETHOGs-2.0",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "tool_id": "QfO:GETHOGs-2.0"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/metrics_events/MetricsEvent_BLCA_e-Driver_TPR_OEBA002t00008J.json
{
    "_id": "TCGA:2018-04-05_BLCA_metricsEvent_e-Driver_TPR",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "TCGA:2018-04-05_BLCA",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "TCGA:2018-04-05_BLCA_M",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_BLCA_P_e-Driver",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_BLCA_A_TPR_e-Driver",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "TCGA:e-Driver"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/MetricsEvents/MetricsEvent_CESC_compositeDriver_TPR_OEBA002t000097.json
{
    "_id": "OEBA002t000097",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "OEBX002t000004",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t00007W",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t00000Q",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000A6",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_CESC_metricsEvent_compositeDriver_TPR",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000003"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/MetricsEvents/MetricsEvent_BLCA_2020plus_TPR_OEBA002t00008D.json
{
    "_id": "OEBA002t00008D",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "OEBX002t000002",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t00007U",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t00000B",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t00009C",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_BLCA_metricsEvent_2020plus_TPR",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000001"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_LAML_compositeDriver_OEBA002t0000QA.json
{
    "_id": "OEBA002t0000QA",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000E",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000EM",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000EN",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000R9",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_LAML_compositeDriver_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000003"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_COAD_2020plus_OEBA002t0000OJ.json
{
    "_id": "OEBA002t0000OJ",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t000006",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000B4",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000B5",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000PI",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_COAD_2020plus_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000001"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_PCPG_e-Driver_OEBA002t0000SE.json
{
    "_id": "OEBA002t0000SE",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000N",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000IU",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000IV",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000TD",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_PCPG_e-Driver_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000004"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/QfO/metrics_events/MetricsEvent_ECtest_InParanoidCore_ECTest_schlicker.json
{
    "_id": "QfO:2011-07-07_ECtest_metricsEvent_InParanoidCore_ECTest_schlicker",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "QfO:2011-07-07_ECtest",
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "reception": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_ECtest_M",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_P_InParanoidCore",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_ECtest_A_ECTest_schlicker_InParanoidCore",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "Christophe.Dessimoz",
        "Paul.Thomas",
        "Toni.Gabaldon",
        "Erik.Sonnhammer"
    ],
    "tool_id": "QfO:InParanoidCore"
}
