=== inab/benchmarking-data-model/json-schemas/1.0.x/testAction.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Test Action concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the test action, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"pattern": "^OEBA[0-9]{3}t[A-Z0-9]{6}$",
					"description": "Temporary identifiers internally used must follow this pattern",
					"readOnly": true
				},
				{
					"pattern": "^OEBA[0-9]{3}[A-Z0-9]{7}$",
					"description": "Identifiers returned by the APIs must follow this pattern",
					"readOnly": true
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction" ]
		},
		"_metadata": {
			"$ref": "_shared#/definitions/Metadata"
		},
		"orig_id": {
			"title": "The test action original id",
			"$ref": "_shared#/definitions/OriginalId"
		},
		"tool_id": {
			"title": "The id of the processing tool",
			"description": "The id of the tool which processes a set of datasets for this action. Most of the time is a participant's tool, but in the case of aggregation or statistic events, is a tool related to a kind of challenge's metrics",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Tool",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"action_type": {
			"title": "The type of action",
			"description": "The type of action performed by the tool, also describing the kind of input datasets.\nTest Event = Input + Tool -> Participant Data\nMetrics event = Participant Data + Metrics -> Assessment Data\nStatistics event = Assessment Data + Metrics -> Challenge Data\n",
			"type": "string",
			"enum": [ "SetupEvent", "MetricsEvent", "StatisticsEvent", "AggregationEvent", "TestEvent" ]
		},
		"involved_datasets": {
			"title": "The incoming, outgoing and settings datasets involved in this test action",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"dataset_id": {
						"title": "A received dataset, with this id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Dataset",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"role": {
						"title": "The kind of dataset received for this action (report, metrics_reference, etc...)",
						"type": "string",
						"enum": [
							"incoming",
							"outgoing",
							"settings",
							"unknown"
						]
					},
					"received": {
						"title": "Reception date of the dataset (redundant, as the output dataset already has this date)",
						"type": "string",
						"format": "date-time"
					}
				},
				"required": [ "dataset_id", "role" ]
			}
		},
		"challenge_id": {
			"title": "The id of the challenge where this test action was generated",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Challenge",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"test_contact_ids": {
			"title": "Contact id(s) related to the action",
			"description": "The test action contact id(s), i.e. the runners of the tool and depositors of the results",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"status": {
			"title": "The lifecicle of the testAction will be managed by the API, validating it is progressing forward instead of backward",
			"type": "string",
			"enum": [ "scheduled", "sent", "incomplete", "complete", "failed" ]
		},
		"dates": {
			"title": "Relevant dates for this test action",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this test action becomes public",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation"]
		},
		"metadata": {
			"title": "Relevant metadata used to call the tool",
			"type": "object",
			"minProperties": 1,
			"additionalProperties": true
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","involved_datasets","challenge_id","test_contact_ids","dates"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_LGG_OncodriveFM_OEBA002t0000QK.json
{
    "_id": "OEBA002t0000QK",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000F",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000F6",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000F7",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000RJ",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_LGG_OncodriveFM_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000008"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/TestEvents/TestEvent_CESC_e-Driver_OEBA002t00000U.json
{
    "_id": "OEBA002t00000U",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "TestEvent",
    "challenge_id": "OEBX002t000004",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002000000L",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t00000U",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_CESC_testEvent_e-Driver",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000004"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/MetricsEvents/MetricsEvent_KICH_MutSig2CV_precision_OEBA002t0000CA.json
{
    "_id": "OEBA002t0000CA",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "OEBX002t00000B",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t000083",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t000029",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000D9",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_KICH_metricsEvent_MutSig2CV_precision",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000006"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_SKCM_e-Driver_OEBA002t0000TA.json
{
    "_id": "OEBA002t0000TA",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000R",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000KM",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000KN",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000U9",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_SKCM_e-Driver_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000004"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_ALL_e-Driver_OEBA002t0000V2.json
{
    "_id": "OEBA002t0000V2",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000Z",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000O6",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000O7",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000W1",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_ALL_e-Driver_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000004"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_DLBC_MutSig2CV_OEBA002t0000OP.json
{
    "_id": "OEBA002t0000OP",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t000007",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000BG",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000BH",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000PO",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_DLBC_MutSig2CV_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000006"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_THYM_OncodriveCLUST_OEBA002t0000U7.json
{
    "_id": "OEBA002t0000U7",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t00000V",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000MG",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000MH",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000V6",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_THYM_OncodriveCLUST_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000007"
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/StatisticsEvents/StatisticsEvent_ESCA_compositeDriver_OEBA002t0000OY.json
{
    "_id": "OEBA002t0000OY",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/TestAction",
    "action_type": "StatisticsEvent",
    "challenge_id": "OEBX002t000008",
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "reception": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "OEBD002t0000BY",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000BZ",
            "role": "incoming"
        },
        {
            "dataset_id": "OEBD002t0000PX",
            "role": "outgoing"
        }
    ],
    "orig_id": "TCGA:2018-04-05_ESCA_compositeDriver_do_summary",
    "test_contact_ids": [
        "Matthew.Bailey",
        "Eduard.Porta",
        "Collin.Tokheim"
    ],
    "tool_id": "OEBT0020000003"
}
