=== inab/benchmarking-data-model/json-schemas/1.0.x/tool.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Tool",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Tool concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the tool, according to the rules. For submissions there are temporary identifiers",
			"type": "string",
			"oneOf": [
				{
					"pattern": "^OEBT[0-9]{3}t[A-Z0-9]{6}$",
					"writeOnly": true
				},
				{
					"pattern": "^OEBT[0-9]{3}[A-Z0-9]{7}$",
					"readOnly": true
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Tool" ]
		},
		"registry_tool_id": {
			"title": "The unique id of the tool (in bio.tools, bioconda, biocontainers, OpenEBench, etc...), in CURIE format",
			"type": "string",
			"format": "uri"
		},
		"name": {
			"title": "Short tool name",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long tool name or description",
			"type": "string"
		},
		"is_automated": {
			"title": "Can this tool be automatically invoked?",
			"type": "boolean"
		},
		"tool_contact_ids": {
			"title": "The tool's contact id(s), i.e. the creators",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"status": {
			"title": "Current tool status",
			"type": "string",
			"enum": ["unknown","online","offline","unmaintained"],
			"minLength": 1
		},
		"activation": {
			"title": "Activation by the benchmarking community",
			"type": "string",
			"format": "date-time"
		},
		"deactivation": {
			"title": "Deactivation by the benchmarking community",
			"type": "string",
			"format": "date-time"
		},
		"references": {
			"title": "The tool's reference id(s)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"tool_access": {
			"title": "Methods to access the tool",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "object",
				"properties": {
					"tool_access_type": {
						"title": "The tool access type",
						"type": "string",
						"enum": [ "command-line", "REST/OpenAPI", "SOAP/WSDL", "Web", "other" ],
						"minLength": 1
					},
					"link": {
						"title": "The base link to the access point (when it is not a local algorithm)",
						"type": "string",
						"format": "uri"
					},
					"techdocs": {
						"title": "Optional technical documentation of the tool access",
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"uri": {
									"title": "The URI of the technical documentation",
									"type": "string",
									"format": "uri"
								},
								"label": {
									"title": "The type of URI (WSDL, WADL, OpenAPI/Swagger, Source code, Miscellaneous documentation)",
									"type": "string",
									"enum": ["WSDL","WADL","OpenAPI","API","source","doc"]
								}
							},
							"additionalProperties": false,
							"required": [
								"uri",
								"label"
							]
						}
					}
				},
				"additionalProperties": true,
				"required": [
					"tool_access_type"
				]
			}
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","name","is_automated","tool_contact_ids","status","tool_access"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/1.0.x/TCGA/Tools/Tool_OncodriveCLUST.json
{
    "_id":"OEBT0020000007",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Tool",
    "activation": "2018-04-05T00:00:00.000+0000",
    "description": "Cancer Driver Genes prediction",
    "is_automated": true,
    "name": "OncodriveCLUST",
    "references": [
        "doi:10.1093/bioinformatics/btt395"
    ],
    "status": "unknown",
    "tool_access": [
        {
            "tool_access_type": "other"
        }
    ],
    "tool_contact_ids": [
        "David.Tamborero"
    ]
}
