=== inab/benchmarking-data-model/json-schemas/2.0.x/dataset.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Dataset",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Dataset concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$ref": "_shared#/definitions/OrigIdProp"
		},
		{
			"$ref": "_shared#/definitions/ReferencesProp"
		},
		{
			"$ref": "_shared#/definitions/LinksDescProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the dataset, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"$ref": "_shared#/definitions/DatasetTemporaryId"
				},
				{
					"$ref": "_shared#/definitions/DatasetId"
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of '$id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Dataset" ]
		},
		
		"@canonical_id": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys",
			"$ref": "_shared#/definitions/DatasetCanonicalId"
		},
		"_metadata": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@revision": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@updated": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@deleted": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@created": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"orig_id": {
			"$comment": "Placeholder covered by _shared#/definitions/OrigIdProp",
			"title": "The dataset original id"
		},
		"references": {
			"$comment": "Placeholder covered by _shared#/definitions/ReferencesProp",
			"title": "The reference id(s) of this dataset (if any)"
		},
		"name": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksDescProp",
			"title": "Short dataset name"
		},
		"description": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksDescProp",
			"title": "Long dataset description, written in Markdown"
		},
		
		"community_ids": {
			"title": "The communities where this dataset was generated or used",
			"description": "This field is redundant, as it can be obtained from the challenges",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				]
			}
		},
		"challenge_ids": {
			"title": "The challenge(s) where this dataset was generated or used",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Challenge",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"visibility": {
			"title": "The visibility of this dataset, which must be acknowledged by the APIs",
			"type": "string",
			"enum": [ "public", "community", "challenge" ]
		},
		"version": {
			"title": "Version (or relelase date) of the dataset",
			"minLength": 1,
			"type": "string"
		},
		"dates": {
			"title": "Relevant dates for this dataset",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this dataset becomes public",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation","modification"]
		},
		"type": {
			"title": "Type of dataset. Aggregation datasets are combinations of other aggregations or assessments.",
			"type": "string",
			"mingLength": 1,
			"enum": [ "public_reference", "metrics_reference", "input", "participant", "assessment", "participant_assessments", "aggregation", "other" ]
		},
		"datalink": {
			"title": "The data itself, either linked or embedded",
			"type": "object",
			"oneOf": [
				{
					"title": "Inline, embedded data",
					"properties": {
						"inline_data": {
							"title": "Inline data in JSON format",
							"type": "object",
							"minProperties": 1,
							"additionalProperties": true
						},
						"schema_url": {
							"title": "The optional URL to the JSON Schema which validates the inline data. It could be embedded, using the data: protocol encoding",
							"type": "string",
							"format": "uri"
						}
					},
					"additionalProperties": false,
					"required": [ "inline_data" ]
				},
				{
					"title": "The link to reach the dataset",
					"properties": {
						"uri": {
							"title": "Either inline, encoded data URI; or an official CURIE; or download link to the dataset itself; or a link to a Metalink describing the dataset; or a link to a MD5/SHA1 sums file with relative paths",
							"type": "string",
							"format": "uri"
						},
						"attrs": {
							"title": "Attributes describing the datalink: whether it is inline (i.e. a data URI); a CURIE; whether it is compressed, or an archive (tar, zip, rar), a metalink (RFC 5854, RFC 6249, https://en.wikipedia.org/wiki/Metalink) or a standard sums (MD5, SHA1) file",
							"type": "array",
							"minItems": 1,
							"uniqueItems": true,
							"anyOf": [
								{
									"items": {
										"type": "string",
										"enum": [ "inline","compressed", "archive", "metalink", "sums" ]
									}
								},
								{
									"items": {
										"type": "string",
										"enum": [ "curie", "compressed", "archive", "metalink" ]
									}
								}
							]
						},
						"validation_date": {
							"title": "Last validation date of the datalink",
							"type": "string",
							"format": "date-time"
						},
						"status": {
							"title": "Last validation status (unreachable content, missing content(404), interrupted while validating, corrupted (checksums, not all the contents available, etc...), ok)",
							"type": "string",
							"enum": [ "unreachable", "missing", "interrupted", "corrupted", "ok" ]
						}
					},
					"additionalProperties": false,
					"required": [ "uri", "attrs" ]
				}
			]
		},
		"dataset_contact_ids": {
			"title": "The contact id(s) of the depositor(s)/creator(s) of this dataset",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"depends_on": {
			"title": "The causal, direct dependencies of this dataset on a tool and other datasets, if available",
			"type": "object",
			"properties": {
				"metrics_id": {
					"title": "The id of the metrics tied to the tool id",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Metrics",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"tool_id": {
					"title": "The id of the tool which generated this dataset",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Tool",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"rel_dataset_ids": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"dataset_id": {
								"title": "The id of a dataset which was used to generate this new dataset",
								"type": "string",
								"foreign_keys": [
									{
										"schema_id": "Dataset",
										"members": [ "." ]
									}
								],
								"minLength": 1
							},
							"role": {
								"title": "The role of the referenced dataset generating the current one (used to generate the current dataset, superseded by the generated dataset, ....)",
								"type": "string",
								"enum": [ "dependency", "superseded", "report" ],
								"default": "dependency"
							}
						},
						"required": [ "dataset_id" ]
					}
				}
			},
			"required": [ "rel_dataset_ids" ]
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","challenge_ids","visibility","name","version","type","dates","datalink","dataset_contact_ids"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/reference_datasets/Dataset_Metrics_Ref_TreeFam-A.json
{
    "_id": "QfO:2011-07-07_TreeFam-A_M",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_TreeFam-A"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "attrs": [
            "archive"
        ],
        "status": "ok",
        "uri": "http://www.treefam.org/",
        "validation_date": "2011-07-07T00:00:00Z"
    },
    "dataset_contact_ids": [
        "orcid:0000-0002-2170-853X",
        "orcid:0000-0002-9074-3507",
        "orcid:0000-0003-0019-1735",
        "orcid:0000-0002-9015-5588"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_I"
            }
        ]
    },
    "description": "Gene Tree that can be used in the TreeFam-A benchmark as reference to assess the accuracy of orthologs predicted",
    "name": "Metrics Reference Dataset for Agreement with Reference Gene Phylogenies: TreeFam-A benchmark",
    "type": "metrics_reference",
    "version": "unknown",
    "visibility": "community"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/participant_datasets/Dataset_participant_HNSC_MutSig2CV_OEBD002t000021.json
{
    "_id": "TCGA:2018-04-05_HNSC_P_MutSig2CV",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Dataset",
    "challenge_ids": [
        "TCGA:2018-04-05_HNSC"
    ],
    "community_ids": [
        "OEBC001"
    ],
    "datalink": {
        "attrs": [
            "archive"
        ],
        "status": "ok",
        "uri": "https://api.gdc.cancer.gov/data/2e8d4650-5498-4288-a461-23667ff553e2",
        "validation_date": "2018-04-05T00:00:00Z"
    },
    "dataset_contact_ids": [
        "orcid:0000-0001-7900-4239"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z"
    },
    "depends_on": {
        "rel_dataset_ids": [
            {
                "dataset_id": "TCGA:2018-04-05_input"
            }
        ],
        "tool_id": "TCGA:MutSig2CV"
    },
    "description": "List of Cancer Driver Genes predicted by tool MutSig2CV in Head and Neck Squamous Cell Carcinoma",
    "name": "Cancer Driver Genes in Head and Neck Squamous Cell Carcinoma",
    "type": "participant",
    "version": "unknown",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/Dataset_Input.json
{
    "_id": "QfO:2011-07-07_I",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Dataset",
    "community_ids": ["OEBC002"],
    "visibility": "public",
    "challenge_ids": [
	"QfO:2011-07-07_SwissTree",
	"QfO:2011-07-07_STD_Fungi",
	"QfO:2011-07-07_STD_Eukaryota",
	"QfO:2011-07-07_GOtest",
	"QfO:2011-07-07_TreeFam-A",
	"QfO:2011-07-07_G_STD_Fungi",
	"QfO:2011-07-07_G_STD_Eukaryota",
	"QfO:2011-07-07_G_STD_LUCA",
	"QfO:2011-07-07_G_STD_Vertebrata",
	"QfO:2011-07-07_ECtest"
    ],
    "datalink": {
        "attrs": [
            "archive"
        ],
        "status": "ok",
        "uri": "ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/",
        "validation_date": "2011-07-07T00:00:00Z"
    },
    "dataset_contact_ids": [
	"orcid:0000-0002-2170-853X",
        "orcid:0000-0002-9074-3507",
        "orcid:0000-0003-0019-1735",
        "orcid:0000-0002-9015-5588"

    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "description": "Reference proteome used by QfO participants as input dataset for orthologs prediction ",
    "name": "Quest for Orthologs Reference Proteome - 2011",
    "type": "input",
    "version": "2011"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/assessment_datasets/Dataset_assessment_ESCA_MuSiC_TPR_OEBD002t0000CA.json
{
    "_id": "TCGA:2018-04-05_ESCA_A_TPR_MuSiC",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Dataset",
    "challenge_ids": [
        "TCGA:2018-04-05_ESCA"
    ],
    "community_ids": [
        "OEBC001"
    ],
    "datalink": {
        "inline_data": {
            "value": 0.42857142857142855
        }
    },
    "dataset_contact_ids": [
        "orcid:0000-0002-1825-0090"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "TCGA:TPR",
        "rel_dataset_ids": [
            {
                "dataset_id": "TCGA:2018-04-05_ESCA_P_MuSiC"
            },
            {
                "dataset_id": "TCGA:2018-04-05_ESCA_M"
            }
        ],
        "tool_id": "TCGA:MuSiC"
    },
    "description": "Assessment dataset for applying Metric 'True Positive Rate' to MuSiC predictions in Esophageal Carcinoma",
    "name": "Assesment of Metric TPR in MuSiC",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/assessment_datasets/Dataset_assessment_STD_Eukaryota_Orthoinspector-1.30_STD_num_orthologs.json
{
    "_id": "QfO:2011-07-07_STD_Eukaryota_A_STD_num_orthologs_Orthoinspector-1.30",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Dataset",
    "challenge_ids": [
        "QfO:2011-07-07_STD_Eukaryota"
    ],
    "community_ids": [
        "OEBC002"
    ],
    "datalink": {
        "inline_data": {
            "error": 0,
            "value": 268825.0
        }
    },
    "dataset_contact_ids": [
        "orcid:0000-0002-2170-853X",
        "orcid:0000-0002-9074-3507",
        "orcid:0000-0003-0019-1735",
        "orcid:0000-0002-9015-5588"
    ],
    "dates": {
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T14:00:00Z"
    },
    "depends_on": {
        "metrics_id": "QfO:STD_num_orthologs",
        "rel_dataset_ids": [
            {
                "dataset_id": "QfO:2011-07-07_P_Orthoinspector-1.30"
            },
            {
                "dataset_id": "QfO:2011-07-07_STD_Eukaryota_M"
            }
        ],
        "tool_id": "QfO:Orthoinspector-1.30"
    },
    "description": "Assessment dataset for applying Metric 'STD_num_orthologs' to Orthoinspector-1.30 predictions in Species Tree Discordance in Eukaryota",
    "name": "Assesment of STD_num_orthologs in Orthoinspector-1.30",
    "type": "assessment",
    "version": "1",
    "visibility": "public"
}
