=== inab/benchmarking-data-model/json-schemas/2.0.x/reference.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Reference",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Bibliographic reference concept (OpenEBench Benchmarking Data Model schemas)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$comment": "It declares _canonical_id, _metadata, _revision, _license, _provenance",
			"$ref": "_shared#/definitions/CommonKeys"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"$ref": "_shared#/definitions/ReferenceCanonicalId"
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Reference" ]
		},
		"dependable_community_ids": {
			"title": "Dependable community ids",
			"description": "The communities which could depend on this manuscript's knowledge. This list is only informative, because the list can only be managed by administrators",
			"type": "array",
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				],
				"minLength": 1
			},
			"uniqueItems": true,
			"minItems": 1
		},
		
		"title": {
			"title": "The title of the referenced material",
			"type": "string"
		},
		"bibliographic_ids": {
			"title": "The recorded bibliographic ids of the referenced material, as CURIE/identifiers.org format or a bare link",
			"type": "array",
			"minItems": 1,
			"items": {
				"title": "Currently, the accepted ids are pmid, doi and pmc",
				"type": "string",
				"format": "uri",
				"pattern": "^(pmid|pubmed|doi|pmc|isbn|issn|http(s)?):.+$"
			}
		},
		"abstract": {
			"title": "Optionally, the abstract of the referenced material",
			"type": "string"
		},
		"authors": {
			"title": "Optional list of authors of the referenced material",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"publishName": {
						"title": "Name of the author as it appears at the publication",
						"type": "string",
						"minLength": 1
					},
					
					"orcid": {
						"title": "If an orcid exists for this author in the publication, the orcid itself",
						"type": "string",
						"pattern": "^orcid:0",
						"minLength": 1
					}
				},
				"additionalProperties": false,
				"required": [
					"publishName"
				]
			}
		}
	},
	"unevaluatedProperties": false,
	"required": ["_id","_schema","title","bibliographic_ids"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/References/QfO_reference31.json
{
	"_id":"doi:10.1093/bib/bbr034",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Reference",
	"title": "Conceptual framework and pilot study to benchmark phylogenomic databases based on reference gene trees",
	"bibliographic_ids":["doi:10.1093/bib/bbr034"],
	"abstract": "Phylogenomic databases provide orthology predictions for species with fully sequenced genomes. Although the goal seems well-defined, the content of these databases differs greatly. Seven ortholog databases (Ensembl Compara, eggNOG, HOGENOM, InParanoid, OMA, OrthoDB, Panther) were compared on the basis of reference trees. For three well-conserved protein families, we observed a generally high specificity of orthology assignments for these databases. We show that differences in the completeness of predicted gene relationships and in the phylogenetic information are, for the great majority, not due to the methods used, but to differences in the underlying database concepts. According to our metrics, none of the databases provides a fully correct and comprehensive protein classification. Our results provide a framework for meaningful and systematic comparisons of phylogenomic databases. In the future, a sustainable set of 'Gold standard' phylogenetic trees could provide a robust method for phylogenomic databases to assess their current quality status, measure changes following new database releases and diagnose improvements subsequent to an upgrade of the analysis procedure."
}
