=== inab/benchmarking-data-model/json-schemas/2.0.x/tool.json
{
	"$id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Tool",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Tool concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$ref": "_shared#/definitions/OrigIdProp"
		},
		{
			"$ref": "_shared#/definitions/ReferencesProp"
		},
		{
			"$ref": "_shared#/definitions/LinksDescProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the tool, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"$ref": "_shared#/definitions/ToolTemporaryId"
				},
				{
					"$ref": "_shared#/definitions/ToolId"
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Tool" ]
		},
		
		"@canonical_id": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys",
			"$ref": "_shared#/definitions/ToolCanonicalId"
		},
		"_metadata": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@revision": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@updated": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@deleted": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"@created": {
			"$comment": "Placeholder covered by _shared#/definitions/CommonKeys"
		},
		"orig_id": {
			"$comment": "Placeholder covered by _shared#/definitions/OrigIdProp",
			"title": "The tool original (community) id"
		},
		"references": {
			"$comment": "Placeholder covered by _shared#/definitions/ReferencesProp",
			"title": "The reference id(s) of this tool (if any)"
		},
		"links": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksDescProp",
			"title": "Optional links related to the metrics"
		},
		"name": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksDescProp",
			"title": "Short tool name"
		},
		"description": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksDescProp",
			"title": "Long tool description, in Markdown format"
		},
		
		"registry_tool_id": {
			"title": "The unique id of the tool (in bio.tools, bioconda, biocontainers, OpenEBench, etc...), in CURIE format",
			"type": "string",
			"format": "uri"
		},
		"community_ids": {
			"title": "The community/es where this tool is being used",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"is_automated": {
			"title": "Can this tool be automatically invoked?",
			"type": "boolean"
		},
		"tool_contact_ids": {
			"title": "The tool's contact id(s), i.e. the creators",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"status": {
			"title": "Current tool status",
			"type": "string",
			"enum": ["unknown","online","offline","unmaintained"],
			"minLength": 1
		},
		"activation": {
			"title": "Activation by the benchmarking community",
			"type": "string",
			"format": "date-time"
		},
		"deactivation": {
			"title": "Deactivation by the benchmarking community",
			"type": "string",
			"format": "date-time"
		},
		"tool_access": {
			"title": "Methods to access the tool",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"tool_access_type": {
						"title": "The tool access type",
						"type": "string",
						"enum": [ "command-line", "REST/OpenAPI", "SOAP/WSDL", "Web", "other" ],
						"minLength": 1
					},
					"link": {
						"title": "The base link to the access point (when it is not a local algorithm)",
						"type": "string",
						"format": "uri"
					},
					"techdocs": {
						"title": "Optional technical documentation of the tool access",
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "object",
							"properties": {
								"uri": {
									"title": "The URI of the technical documentation",
									"type": "string",
									"format": "uri"
								},
								"label": {
									"title": "The type of URI (WSDL, WADL, OpenAPI/Swagger, Source code, Miscellaneous documentation)",
									"type": "string",
									"enum": ["WSDL","WADL","OpenAPI","API","source","doc"]
								}
							},
							"additionalProperties": false,
							"required": [
								"uri",
								"label"
							]
						}
					}
				},
				"additionalProperties": true,
				"required": [
					"tool_access_type"
				]
			}
		}
	},
	"additionalProperties": false,
	"required": ["_id","_schema","name","community_ids","is_automated","tool_contact_ids","status","tool_access"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/Tools/Tool_EnsemblCompara-e56.json
{
    "_id": "QfO:EnsemblCompara-e56",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Tool",
    "activation": "2011-07-07T00:00:00Z",
    "community_ids": [
        "OEBC002"
    ],
    "description": "Modified version of the vanilla pipeline to build trees with protein sequences only (no nucleotide sequence, no chromosome coordinates).Please be aware that the Xenopus tropicalis genes homologies are mostly wrong due to an error in the species tree used in the pipeline ",
    "is_automated": true,
    "name": "EnsemblCompara-e56",
    "references": [
        "doi:10.1038/nmeth.3830"
    ],
    "status": "unknown",
    "tool_access": [
        {
            "link": "http://www.ensembl.org",
            "tool_access_type": "other"
        }
    ],
    "tool_contact_ids": [
        "orcid:0000-0002-2170-853X"
    ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/Tools/Tool_OMA-Pairs-2.0.json
{
    "_id": "QfO:OMA-Pairs-2.0",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/2.0/Tool",
    "activation": "2011-07-07T00:00:00Z",
    "community_ids": [
        "OEBC002"
    ],
    "description": "The OMA Pairs are the primary product of the OMA pipeline. It is a list of high-confidence pairs of orthologous genes.OMA is based on an algorithm that compares genes on the basis of evolutionary distances, considers distance inference uncertainty, and accounts for differential gene losses.The version 2.0 has better support for fast evolving inparalogs. The changes are described in here. ",
    "is_automated": true,
    "name": "OMA-Pairs-2.0",
    "references": [
        "doi:10.1038/nmeth.3830"
    ],
    "status": "unknown",
    "tool_access": [
        {
            "link": "http://omabrowser.org",
            "tool_access_type": "other"
        }
    ],
    "tool_contact_ids": [
        "orcid:0000-0002-2170-853X"
    ]
}
