=== inab/benchmarking-data-model/json-schemas/0.3.x/benchmarkingEvent.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/BenchmarkingEvent",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Benchmarking Event concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the benchmarking event. If it is possible, it should be something meaningful, like an URL",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/BenchmarkingEvent" ]
		},
		"name": {
			"title": "Short benchmarking event name",
			"minLength": 1,
			"type": "string"
		},
		"is_automated": {
			"title": "Is this an automated event?",
			"type": "boolean"
		},
		"dates": {
			"title": "Relevant dates for this benchmarking event",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the benchmarking event",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the benchmarking event",
					"type": "string",
					"format": "date-time"
				},
				"benchmark_start": {
					"title": "When starts the benchmarking event?",
					"type": "string",
					"format": "date-time"
				},
				"benchmark_stop": {
					"title": "When stops the benchmarking event?",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation","modification"],
			"dependencies": {
				"benchmark_start": ["benchmark_stop"],
				"benchmark_stop": ["benchmark_start"]
			}
		},
		"url": {
			"title": "The link to the benchmarking event",
			"type": "string",
			"format": "uri"
		},
		"community_id": {
			"title": "The community id where this benchmarking event belongs",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Community",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"bench_contact_id": {
			"title": "The benchmarking event contact id(s)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"references": {
			"title": "The benchmarking event reference id(s) (if any)",
			"type": "array",
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","name","is_automated","dates","community_id","bench_contact_id"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/QfO_benchmarkingEvent_STD.json
{
	"_id": "QfO:QfO4_STD",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/BenchmarkingEvent",
	"name": "Quest for Orthologs 4 - Species Tree Discordance",
	"is_automated": true,
	"dates": {
		"creation": "2015-01-01T00:00:01Z",
		"modification": "2015-01-01T00:00:01Z",
		"benchmark_start": "2015-01-01T00:00:01Z",
		"benchmark_stop": "2015-04-14T23:59:59Z"
	},
	"url": "http://genome.crg.es/~tgabaldon/QfO4/index.html",
	"community_id": "QfO:QfO",
	"bench_contact_id": [
		"Christophe.Dessimoz",
		"Paul.Thomas",
		"Toni.Gabaldon",
		"Erik.Sonnhammer"
	],
	"references": [
		"10.1038/nmeth.3830"
	]
}
