=== inab/benchmarking-data-model/json-schemas/0.3.x/community.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Community",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Community concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the community. It should be something unique of the community (for instance, an acronym)",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Community" ]
		},
		"name": {
			"title": "Short community name",
			"minLength": 1,
			"type": "string"
		},
		"acronym": {
			"title": "Unique community acronym",
			"minLength": 1,
			"type": "string"
		},
		"status_id": {
			"title": "_id(s) of the current community status(es)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "CommunityStatus",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"description": {
			"title": "Long community name or description",
			"type": "string"
		},
		"links": {
			"title": "Optional links related to the community",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"title": "The URI of the link related to the community",
						"type": "string",
						"format": "uri"
					},
					"label": {
						"title": "The type of URI",
						"type": "string",
						"enum": ["PublicationDOI","LinkedInGroup","MainSite","DataSite"]
					}
				},
				"additionalProperties": false,
				"required": [
					"uri",
					"label"
				]
			}
		},
		"community_contacts": {
			"title": "_id of the contacts of the responsible researchers in charge of the community coordination",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","name","acronym","status_id","community_contacts"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/Biocreative-prototype-data/BioCreative_community.json
{
	"_id": "BioCreative",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Community",
	"name": "BioCreative: Critical Assessment of Information Extraction in Biology",
	"acronym": "BioCreative",
	"status_id": [
		"Active"
	],
	"description": "BioCreative: Critical Assessment of Information Extraction in Biology is a community-wide effort for evaluating text mining and information extraction systems applied to the biological domain.  One key goal of BioCreative is the active involvement of the text mining user community in the design of the tracks, preparation of corpus and the testing of interactive systems.",
	"links": [
		{
			"label": "MainSite",
			"uri": "http://www.biocreative.org/"
		},
		{
			"label": "PublicationDOI",
			"uri": "http://dx.doi.org/10.1186/gb-2008-9-s2-s6"
		},
		{
			"label": "PublicationDOI",
			"uri": "http://dx.doi.org/10.1002/cfg.337"
		},
		{
			"label": "PublicationDOI",
			"uri": "http://dx.doi.org/10.1186/gb-2008-9-s2-s8"
		},
		{
			"label": "DataSite",
			"uri": "http://www.biocreative.org/"
		}
	],
	"community_contacts": [
		"Martin.Krallinger",
		"Analia.Louren√ßo"
	]
}
