=== inab/benchmarking-data-model/json-schemas/0.3.x/contact.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Contact",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Contact concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the contact. It should be whatever ELIXIR AAI uses as public unique user id (for instance, a URI)",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Contact" ]
		},
		"contact_type": {
			"title": "Type of contact: physical person, helpdesk, other",
			"type": "string",
			"enum": [ "person", "helpdesk", "other" ]
		},
		"givenName": {
			"title": "First / given name",
			"type": "string",
			"minLength": 1
		},
		"surname": {
			"title": "Surname(s)",
			"type": "string",
			"minLength": 1
		},
		"email": {
			"title": "The e-mail address(es) of the contact",
			"type": "array",
			"format": "email",
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "string",
				"minLength": 1,
				"format": "email"
			}
		},
		"notes": {
			"title": "Comments about the contact",
			"type": "string"
		},
		"links": {
			"title": "Optional links related to the contact",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"title": "The URI of the link related to the contact",
						"type": "string",
						"format": "uri"
					},
					"label": {
						"title": "The type of URI",
						"type": "string",
						"enum": ["LinkedIn","ORCID","MainSite","Twitter","Other"]
					}
				},
				"additionalProperties": false,
				"required": [
					"uri",
					"label"
				]
			}
		}
	},
	"additionalProperties": true,
	"required": [
		"_id",
		"_schema",
		"contact_type",
		"email"
	],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/QfO_contact6.json
{
	"_id": "Jaime.Huerta-Cepas",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Contact",
	"contact_type": "person",
	"givenName": "Jaime",
	"surname": "Huerta-Cepas",
	"email": [
		"huerta@embl.de",
		"jaime.huerta@embl.de"
	],
	"notes": "EggNOG contact",
	"links": [
		{
			"label": "MainSite",
			"uri": "https://www.embl.de/research/units/scb/bork/members/index.php?s_personId=CP-60017534"
		},
		{
			"label": "ORCID",
			"uri": "https://orcid.org/0000-0003-4195-5025"
		}
	]
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/QfO_contact4.json
{
	"_id": "Toni.Gabaldon",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Contact",
	"contact_type": "person",
	"givenName": "Toni",
	"surname": "Gabaldon",
	"email": [
		"toni.gabaldon@crg.eu"
	],
	"notes": "QfO4 organizer",
	"links": [
		{
			"label": "MainSite",
			"uri": "http://www.crg.eu/es/programmes-groups/comparative-genomics"
		},
		{
			"label": "ORCID",
			"uri": "https://orcid.org/0000-0003-0019-1735"
		}
	]
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/QfO_contact3.json
{
	"_id": "Paul.Thomas",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Contact",
	"contact_type": "person",
	"givenName": "Paul",
	"surname": "Thomas",
	"email": [
		"pdthomas@med.usc.edu"
	],
	"notes": "QfO4 organizer",
	"links": [
		{
			"label": "MainSite",
			"uri": "https://sites.google.com/usc.edu/thomaslab"
		},
		{
			"label": "ORCID",
			"uri": "https://orcid.org/0000-0002-0883-9068"
		}
	]
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/QfO_contact10.json
{
	"_id": "Andreas.Schlicker",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Contact",
	"contact_type": "person",
	"givenName": "Andreas",
	"surname": "Schlicker",
	"email": [
		"schlandi@mpi-inf.mpg.de"
	],
	"notes": "Contact for Schlicker's semantic similarity metric",
	"links": [
		{
			"label": "MainSite",
			"uri": "https://bioinf.mpi-inf.mpg.de/homepage/index.php?&account=schlandi"
		}
	]
}
