=== inab/benchmarking-data-model/json-schemas/0.3.x/dataset.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Dataset concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the dataset. If it is possible, it should be something meaningful",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset" ]
		},
		"name": {
			"title": "Short dataset name",
			"minLength": 1,
			"type": "string"
		},
		"version": {
			"title": "Version (or relelase date) of the dataset",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long dataset description",
			"type": "string"
		},
		"dates": {
			"title": "Relevant dates for this dataset",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the dataset",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation","modification"]
		},
		"type": {
			"title": "Type of dataset",
			"type": "string",
			"mingLength": 1
		},
		"datalink": {
			"title": "The link to the dataset itself",
			"type": "string",
			"format": "uri"
		},
		"dataset_contact_id": {
			"title": "The contact id(s) of the creators of this dataset",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"metrics": {
			"title": "The different metrics generated from this dataset",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"metrics_id": {
						"title": "The id of the metrics as such",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Metrics",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"result": {
						"title": "The results obtained from the metrics",
						"type": "object",
						"additionalProperties": true
					}
				}
			}
		},
		"references": {
			"title": "The reference id(s) of this dataset (if any)",
			"type": "array",
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","name","version","type","dates","dataset_contact_id"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO-prototype-data/QfO_dataset5.json
{
	"_id": "QfO:QfO4_output_RBH-BBH",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
	"name": "RBH__BBH-.621.rels",
	"version": "v1.0",
	"description": "Output data set (pairwise orthologs predictions) for RBH-BBH tool",
	"dates": {
		"creation": "2016-01-12T16:40:11Z",
		"modification": "2016-01-12T16:40:11Z"
	},
	"type": "Output",
	"datalink": "http://orthology.benchmarkservice.org/raw/RBH__BBH-.621.rels.raw.gz",
	"dataset_contact_id": [
		"unknown"
	]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO-prototype-data/QfO_dataset6.json
{
	"_id": "QfO:QfO4_output_RSD",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
	"name": "rsd_0.8_1e-5_deluca_test-.771.rels",
	"version": "v1.0",
	"description": "Output data set (pairwise orthologs predictions) for RSD 0.8 1e-5 Deluca tool",
	"dates": {
		"creation": "2012-02-08T20:28:20Z",
		"modification": "2012-02-08T20:28:20Z"
	},
	"type": "Output",
	"datalink": "http://orthology.benchmarkservice.org/raw/rsd_0.8_1e-5_deluca_test-.771.rels.raw.gz",
	"dataset_contact_id": [
		"ToddF.DeLuca",
		"DennisP.Wall"
	]
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/GOtest_OMA-GETHOGs_output.json
{
    "_id": "QfO:QfO4:GOtest_OMA-GETHOGs_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the OMA-GETHOGs tool in the 'Gene Ontology Conservation Test' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:GOConservationTest-recall",
            "result": {
                "value": 123176
            }
        },
        {
            "metrics_id": "QfO:GOConservationTest-precision",
            "result": {
                "value": 0.4815
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.0012
            }
        }
    ],
    "name": "OMA-GETHOGs.tar.gz",
    "type": "Output",
    "version": "unknown"
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO-prototype-data/QfO_dataset9.json
{
	"_id": "QfO:QfO4_output_PhylomeDB",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
	"name": "phylomeDB-.389.rels",
	"version": "v1.0",
	"description": "Output data set (pairwise orthologs predictions) for PhylomeDB tool",
	"dates": {
		"creation": "2013-06-06T11:51:18Z",
		"modification": "2013-06-06T11:51:18Z"
	},
	"type": "Output",
	"datalink": "http://orthology.benchmarkservice.org/raw/phylomeDB-.389.rels.raw.gz",
	"dataset_contact_id": [
		"Toni.Gabaldon"
	]
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/SwissTree_RBH-BBH_output.json
{
    "_id": "QfO:QfO4:SwissTree_RBH-BBH_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the RBH-BBH tool in the 'Agreement with Reference Gene Phylogenies: SwissTree' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:referenceSwissTree_recall",
            "result": {
                "value": 0.693
            }
        },
        {
            "metrics_id": "QfO:referenceSwissTree_precision",
            "result": {
                "value": 0.9948
            }
        },
        {
            "metrics_id": "QfO:recall_error",
            "result": {
                "value": 0.0541726
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.010077
            }
        }
    ],
    "name": "RBH-BBH.tar.gz",
    "type": "Output",
    "version": "unknown"
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/G_STD_Eukaryota_PANTHER-all_output.json
{
    "_id": "QfO:QfO4:G_STD_Eukaryota_PANTHER-all_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the PANTHER-all tool in the 'Generalized Species Tree Discordance' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:STD-recall1",
            "result": {
                "value": 6724
            }
        },
        {
            "metrics_id": "QfO:STD-precision",
            "result": {
                "value": 0.299
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.011
            }
        }
    ],
    "name": "PANTHER-all.tar.gz",
    "type": "Output",
    "version": "Eukaryota"
}
