=== inab/benchmarking-data-model/json-schemas/0.3.x/dataset.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Dataset concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the dataset. If it is possible, it should be something meaningful",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset" ]
		},
		"name": {
			"title": "Short dataset name",
			"minLength": 1,
			"type": "string"
		},
		"version": {
			"title": "Version (or relelase date) of the dataset",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long dataset description",
			"type": "string"
		},
		"dates": {
			"title": "Relevant dates for this dataset",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the dataset",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the dataset",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation","modification"]
		},
		"type": {
			"title": "Type of dataset",
			"type": "string",
			"mingLength": 1
		},
		"datalink": {
			"title": "The link to the dataset itself",
			"type": "string",
			"format": "uri"
		},
		"dataset_contact_id": {
			"title": "The contact id(s) of the creators of this dataset",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"metrics": {
			"title": "The different metrics generated from this dataset",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"metrics_id": {
						"title": "The id of the metrics as such",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Metrics",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"result": {
						"title": "The results obtained from the metrics",
						"type": "object",
						"additionalProperties": true
					}
				}
			}
		},
		"references": {
			"title": "The reference id(s) of this dataset (if any)",
			"type": "array",
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","name","version","type","dates","dataset_contact_id"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/G_STD_Vertebrata_OMA-GETHOGs_output.json
{
    "_id": "QfO:QfO4:G_STD_Vertebrata_OMA-GETHOGs_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the OMA-GETHOGs tool in the 'Generalized Species Tree Discordance' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:STD-recall1",
            "result": {
                "value": 11549
            }
        },
        {
            "metrics_id": "QfO:STD-precision",
            "result": {
                "value": 0.2057
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.0071
            }
        }
    ],
    "name": "OMA-GETHOGs.tar.gz",
    "type": "Output",
    "version": "Vertebrata"
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/ECtest_OMA-Groups_output.json
{
    "_id": "QfO:QfO4_ECtest_OMA-Groups_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the OMA-Groups tool in the 'Enzyme Classification Conservation Test' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:ECConservationTest-recall",
            "result": {
                "value": 45746
            }
        },
        {
            "metrics_id": "QfO:ECConservationTest-precision",
            "result": {
                "value": 0.98693
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.00072
            }
        }
    ],
    "name": "OMA-Groups.tar.gz",
    "type": "Output",
    "version": "unknown"
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/TreeFam-A_OMA-GETHOGs_output.json
{
    "_id": "QfO:QfO4_TreeFam-A_OMA-GETHOGs_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the OMA-GETHOGs tool in the 'Agreement with Reference Gene Phylogenies: TreeFam-A' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:referenceTreeFam-A_recall",
            "result": {
                "value": 0.5959
            }
        },
        {
            "metrics_id": "QfO:referenceTreeFam-A_precision",
            "result": {
                "value": 0.89
            }
        },
        {
            "metrics_id": "QfO:recall_error",
            "result": {
                "value": 0.00500656
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.00390173
            }
        }
    ],
    "name": "OMA-GETHOGs.tar.gz",
    "type": "Output",
    "version": "unknown"
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO-prototype-data/QfO_dataset15.json
{
	"_id": "QfO:QfO4_output_OMA-Groups",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
	"name": "OMA_Groups_RefSet5-.212.rels",
	"version": "v1.0",
	"description": "Output data set (predicted orthologous groups) for OMA Groups tool. The orthologs pairs are stored in OrthoXML format",
	"dates": {
		"creation": "2011-06-06T18:48:45Z",
		"modification": "2011-06-06T18:48:45Z"
	},
	"type": "Output",
	"datalink": "http://orthology.benchmarkservice.org/raw/OMA_Groups_RefSet5-.212.rels.raw.gz",
	"dataset_contact_id": [
		"Christophe.Dessimoz",
		"Adrian.Altenhoff"
	]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/TreeFam-A_PANTHER-all_output.json
{
    "_id": "QfO:QfO4_TreeFam-A_PANTHER-all_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the PANTHER-all tool in the 'Agreement with Reference Gene Phylogenies: TreeFam-A' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:referenceTreeFam-A_recall",
            "result": {
                "value": 0.6765
            }
        },
        {
            "metrics_id": "QfO:referenceTreeFam-A_precision",
            "result": {
                "value": 0.8743
            }
        },
        {
            "metrics_id": "QfO:recall_error",
            "result": {
                "value": 0.00477283
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.00384535
            }
        }
    ],
    "name": "PANTHER-all.tar.gz",
    "type": "Output",
    "version": "unknown"
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/SwissTree_OMA-GETHOGs_output.json
{
    "_id": "QfO:QfO4_SwissTree_OMA-GETHOGs_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the OMA-GETHOGs tool in the 'Agreement with Reference Gene Phylogenies: SwissTree' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:referenceSwissTree_recall",
            "result": {
                "value": 0.8187
            }
        },
        {
            "metrics_id": "QfO:referenceSwissTree_precision",
            "result": {
                "value": 0.9956
            }
        },
        {
            "metrics_id": "QfO:recall_error",
            "result": {
                "value": 0.0452514
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.00854029
            }
        }
    ],
    "name": "OMA-GETHOGs.tar.gz",
    "type": "Output",
    "version": "unknown"
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/G_STD_LUCA_EnsemblCompara_output.json
{
    "_id": "QfO:QfO4_G_STD_LUCA_EnsemblCompara_output",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
    "dataset_contact_id": [
        "unknown"
    ],
    "dates": {
        "creation": "2015-01-01T00:00:01Z",
        "modification": "2015-01-01T00:00:01Z"
    },
    "description": "Output dataset for the EnsemblCompara tool in the 'Generalized Species Tree Discordance' benchmark event with the correspondent metrics generated from it",
    "metrics": [
        {
            "metrics_id": "QfO:STD-recall1",
            "result": {
                "value": 3806
            }
        },
        {
            "metrics_id": "QfO:STD-precision",
            "result": {
                "value": 0.241
            }
        },
        {
            "metrics_id": "QfO:precision_error",
            "result": {
                "value": 0.015
            }
        }
    ],
    "name": "EnsemblCompara.tar.gz",
    "type": "Output",
    "version": "LUCA"
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO-prototype-data/QfO_dataset2.json
{
	"_id": "QfO:QfO4_input_FASTA",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Dataset",
	"name": "2011_04_reference_proteomes_FASTA-EBI",
	"version": "version 5; 2011_04",
	"description": "Reference Proteome data sets in FASTA format: collection of data providing a representative protein for each gene in the genome of selected species that have been generated annually from the uniProt Knowledgebase (UniProtKB) for the past five years",
	"dates": {
		"creation": "2011-04-01T00:00:00Z",
		"modification": "2011-04-01T00:00:00Z"
	},
	"type": "Input",
	"datalink": "ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/",
	"dataset_contact_id": [
		"Toni.Gabaldon",
		"Erik.Sonnhammer",
		"Christophe.Dessimoz",
		"Paul.Thomas"
	],
	"references": [
		"https://www.ncbi.nlm.nih.gov/pubmed/22102590"
	]
}
