=== inab/benchmarking-data-model/json-schemas/0.3.x/reference.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Reference",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Bibliographic reference concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the bibliographic reference. It should be something meaningful, like its DOI or its PubMedId",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Reference" ]
		},
		"title": {
			"title": "The title of the referenced material",
			"type": "string"
		},
		"doi": {
			"title": "The DOI of the referenced material (in case of books, its ISBN in ISBN-A DOI format)",
			"type": "string"
		},
		"pubmed_id": {
			"title": "The PubMed id of the referenced material (if any)",
			"type": "integer",
			"minimum": 1
		},
		"abstract": {
			"title": "Optionally, the abstract of the referenced material",
			"type": "string"
		},
		"links": {
			"title": "Optional links related to the bibliographic reference",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"title": "The URI of the link related to the bibliographic reference",
						"type": "string",
						"format": "uri"
					},
					"label": {
						"title": "The type of URI",
						"type": "string",
						"enum": ["PublicationDOI","LinkedInGroup","MainSite","DataSite"]
					}
				},
				"additionalProperties": false,
				"required": [
					"uri",
					"label"
				]
			}
		},
		"authors": {
			"title": "Optional list of authors of the referenced material",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"givenName": {
						"title": "First / given name (or initials)",
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "string",
							"minLength": 1
						}
					},
					"surname": {
						"title": "Surname(s)",
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "string",
							"minLength": 1
						}
					},
					"contact_id": {
						"title": "If it is a known contact, its contact id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Contact",
								"members": [ "." ]
							}
						],
						"minLength": 1
					}
				},
				"additionalProperties": false,
				"required": [
					"givenName",
					"surname"
				]
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","title"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/QfO_reference32.json
{
	"_id": "10.1093/nar/gkj118",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Reference",
	"title": "TreeFam: a curated database of phylogenetic trees of animal gene families",
	"doi": "10.1093/nar/gkj118",
	"abstract": "TreeFam is a database of phylogenetic trees of gene families found in animals. It aims to develop a curated resource that presents the accurate evolutionary history of all animal gene families, as well as reliable ortholog and paralog assignments. Curated families are being added progressively, based on seed alignments and trees in a similar fashion to Pfam. Release 1.1 of TreeFam contains curated trees for 690 families and automatically generated trees for another 11 646 families. These represent over 128 000 genes from nine fully sequenced animal genomes and over 45 000 other animal proteins from UniProt; ∼40–85% of proteins encoded in the fully sequenced animal genomes are included in TreeFam. TreeFam is freely available at http://www.treefam.org and http://treefam.genomics.org.cn."
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/Biocreative-prototype-data/Biocreative_reference9.json
{
	"_id": "PMID11825149",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Reference",
	"title": "Effective mapping of biomedical text to the UMLS Metathesaurus: the MetaMap program",
	"pubmed_id": 11825149,
	"abstract": "The UMLS Metathesaurus, the largest thesaurus in the biomedical domain, provides a representation of biomedical knowledge consisting of concepts classified by semantic type and both hierarchical and non-hierarchical relationships among the concepts. This knowledge has proved useful for many applications including decision support systems, management of patient records, information retrieval (IR) and data mining. Gaining effective access to the knowledge is critical to the success of these applications. This paper describes MetaMap, a program developed at the National Library of Medicine (NLM) to map biomedical text to the Metathesaurus or, equivalently, to discover Metathesaurus concepts referred to in text. MetaMap uses a knowledge intensive approach based on symbolic, natural language processing (NLP) and computational linguistic techniques. Besides being applied for both IR and data mining applications, MetaMap is one of the foundations of NLM's Indexing Initiative System which is being applied to both semi-automatic and fully automatic indexing of the biomedical literature at the library."
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/Biocreative-prototype-data/Biocreative_reference11.json
{
	"_id": "10.1093/bioinformatics/btm235",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Reference",
	"title": "MutationFinder: a high-performance system for extracting point mutation mentions from text",
	"doi": "10.1093/bioinformatics/btm235",
	"pubmed_id": 17495998,
	"abstract": "Discussion of point mutations is ubiquitous in biomedical literature, and manually compiling databases or literature on mutations in specific genes or proteins is tedious. We present an open-source, rule-based system, MutationFinder, for extracting point mutation mentions from text. On blind test data, it achieves nearly perfect precision and a markedly improved recall over a baseline. AVAILABILITY: MutationFinder, along with a high-quality gold standard data set, and a scoring script for mutation extraction systems have been made publicly available. Implementations, source code and unit tests are available in Python, Perl and Java. MutationFinder can be used as a stand-alone script, or imported by other applications. PROJECT URL: http://bionlp.sourceforge.net."
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/QfO_reference33.json
{
	"_id": "10.1101/gr.073585.107",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Reference",
	"title": "EnsemblCompara GeneTrees: Complete, duplication-aware phylogenetic trees in vertebrates",
	"doi": "10.1101/gr.073585.107",
	"abstract": "We have developed a comprehensive gene orientated phylogenetic resource, EnsemblCompara GeneTrees, based on a computational pipeline to handle clustering, multiple alignment, and tree generation, including the handling of large gene families. We developed two novel non-sequence-based metrics of gene tree correctness and benchmarked a number of tree methods. The TreeBeST method from TreeFam shows the best performance in our hands. We also compared this phylogenetic approach to clustering approaches for ortholog prediction, showing a large increase in coverage using the phylogenetic approach. All data are made available in a number of formats and will be kept up to date with the Ensembl project."
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/QfO_reference41.json
{
	"_id": "10.1093/bioinformatics/btm295",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Reference",
	"title": "OMA Browserâ€”Exploring orthologous relations across 352 complete genomes",
	"doi": "10.1093/bioinformatics/btm295",
	"abstract": "Motivation: Inference of the evolutionary relation between proteins, in particular the identification of orthologs, is a central problem in comparative genomics. Several large-scale efforts with various methodologies and scope tackle this problem, including OMA (the Orthologous MAtrix project). Results: Based on the results of the OMA project, we introduce here the OMA Browser, a web-based tool allowing the exploration of orthologous relations over 352 complete genomes. Orthologs can be viewed as groups across species, but also at the level of sequence pairs, allowing the distinction among one-to-one, one-to-many and many-to-many orthologs. Availability:http://omabrowser.org"
}
