=== inab/benchmarking-data-model/json-schemas/0.3.x/testEvent.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/TestEvent",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Test Event concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the test event.",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/TestEvent" ]
		},
		"tool_id": {
			"title": "The tool id which takes this input dataset",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Tool",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"input_dataset_id": {
			"title": "The id of the input dataset",
			"type": "string",
			"foreign_keys":  [
				{
					"schema_id": "Dataset",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"output_dataset_id": {
			"title": "The id of the output dataset (if available)",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Dataset",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"benchmarking_event_id": {
			"title": "The id of the benchmarking event where this test event was generated",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "BenchmarkingEvent",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"result_report": {
			"title": "Relevant information about the status changes",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"status": {
						"title": "Status retval",
						"type": "integer"
					},
					"status_date": {
						"title": "Date of the status reception",
						"type": "string",
						"format": "date-time"
					},
					"report": {
						"title": "Textual report for this status",
						"type": "string"
					}
				}
			}
		},
		"dates": {
			"title": "Relevant dates for this test event",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the test event",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the test event",
					"type": "string",
					"format": "date-time"
				},
				"reception": {
					"title": "Last reception date of the output dataset (redundant, as the output dataset already has this date)",
					"type": "string",
					"format": "date-time"
				}
			},
			"required": ["creation"]
		},
		"metadata": {
			"title": "Relevant metadata used to call the tool",
			"type": "object"
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","tool_id","input_dataset_id","benchmarking_event_id","dates"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/SwissTree_OMA-GETHOGs_testEvent.json
{
    "_id": "QfO:QfO4_SwissTree_OMA-GETHOGs",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/TestEvent",
    "benchmarking_event_id": "QfO:QfO4_SwissTree",
    "dates": {
        "creation": "2015-04-14T23:59:59Z"
    },
    "input_dataset_id": "QfO:QfO4_input_seqXML",
    "output_dataset_id": "QfO:QfO4_SwissTree_OMA-GETHOGs_output",
    "tool_id": "QfO:OMA-GETHOGs"
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO-prototype-data/QfO_testEvent_QfO4_InParanoid.json
{
	"_id": "QfO:QfO4_InParanoid",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/TestEvent",
	"tool_id": "QfO:InParanoid",
	"input_dataset_id": "QfO:QfO4_input_seqXML",
	"output_dataset_id": "QfO:QfO4_output_InParanoid",
	"benchmarking_event_id": "QfO:QfO4",
	"dates": {
		"creation": "2015-04-14T23:59:59Z"
	}
}
