=== inab/benchmarking-data-model/json-schemas/0.3.x/tool.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Tool concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the tool. It should be something meaningful, like the tool name, its uri or an acronym",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool" ]
		},
		"bioTools_id": {
			"title": "The unique id of the tool in EXCELERATE WP1 bio.tools registry",
			"type": "string",
			"format": "uri"
		},
		"name": {
			"title": "Short tool name",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long tool name or description",
			"type": "string"
		},
		"is_automated": {
			"title": "Can this tool be automatically invoked?",
			"type": "boolean"
		},
		"community_id": {
			"title": "The community id(s) where this tool belongs",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"tool_contact_id": {
			"title": "The tool's contact id(s)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"status_id": {
			"title": "_id of the current tool status",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "ToolStatus",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"references": {
			"title": "The tool's reference id(s)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"tool_access": {
			"title": "Methods to access the tool",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "object",
				"properties": {
					"tool_access_type_id": {
						"title": "The tool access type id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "ToolAccessType",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"link": {
						"title": "The base link to the access point (when it is not a local algorithm)",
						"type": "string",
						"format": "uri"
					},
					"techdocs": {
						"title": "Optional technical documentation of the tool access",
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"uri": {
									"title": "The URI of the technical documentation",
									"type": "string",
									"format": "uri"
								},
								"label": {
									"title": "The type of URI (WSDL, WADL, OpenAPI/Swagger, Source code, Miscellaneous documentation)",
									"type": "string",
									"enum": ["WSDL","WADL","OpenAPI","API","source","doc"]
								}
							},
							"additionalProperties": false,
							"required": [
								"uri",
								"label"
							]
						}
					}
				},
				"additionalProperties": true,
				"required": [
					"tool_access_type_id"
				]
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","name","is_automated","community_id","tool_contact_id","status_id","tool_access"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/QfO_tool_EggNOG.json
{
	"_id": "QfO:EggNOG",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"name": "EggNOG",
	"description": "A database of orthologous groups and functional annotation",
	"is_automated": true,
	"community_id": ["QfO:QfO"],
	"tool_contact_id": [
		"Jaime.Huerta-Cepas"
	],
	"status_id": "QfO:active",
	"references": [
		"10.1093/nar/gkv1248",
		"10.1093/nar/gkt1253",
		"10.1093/nar/gkr1060",
		"10.1093/nar/gkp951",
		"10.1093/nar/gkm796"
	],
	"tool_access": [
		{
			"tool_access_type_id": "QfO:RESTful-Web-API",
			"link": "http://eggnogapi.embl.de/nog_data/",
			"techdocs": [
				{
					"uri": "http://eggnogdb.embl.de/#/app/api",
					"label": "WADL"
				}
			]
		}
	]
}

=== inab/benchmarking-data-model/prototype-data/QfO_complete_data/QfO_tool_OMA-Groups.json
{
	"_id": "QfO:OMA-Groups",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"name": "OMA Groups",
	"description": "OMA is a publicly available resource (http://omabrowser.org/) that provides orthology predictions among thousands of proteomes from all domains of life. OMA uses evolutionary distance estimates from Smithâ€“Waterman alignments to infer orthologs. A distinct feature among graph-based methods is the witness of nonorthology step in its pipeline, where cases of differential gene losses get detected. OMA provides three different groupings of orthologs: Pairs, Groups, and HOGs. OMA Groups consists of groups of genes in which all pairs are orthologs. In a graph representation with genes as nodes and orthology relations as edge, OMA groups correspond to fully connected subgraphs. Due to this definition, each OMA group includes at most one sequence per species. The primary intended application of these groups is to provide input data for phylogenetic inference.",
	"is_automated": true,
	"community_id": ["QfO:QfO"],
	"tool_contact_id": [
		"Christophe.Dessimoz",
		"Adrian.Altenhoff",
		"OMA.ContactMail"
	],
	"status_id": "QfO:active",
	"references": [
		"10.1093/bioinformatics/btm295",
		"10.1007/978-1-61779-582-4_9",
		"10.1093/nar/gku1158"
	],
	"tool_access": [
		{
			"tool_access_type_id": "QfO:SOAP-Web-API",
			"link": "http://omabrowser.org/oma/APISOAP/",
			"techdocs": [
				{
					"uri": "http://omabrowser.org/omabrowser.wsdl",
					"label": "WSDL"
				}
			]
		},
		{
			"tool_access_type_id": "QfO:Standalone-application",
			"link": "http://omabrowser.org/standalone/OMA.2.1.1.tgz",
			"techdocs": [
				{
					"uri": "http://omabrowser.org/standalone/release_notes.txt",
					"label": "doc"
				},
				{
					"uri": "http://omabrowser.org/standalone/",
					"label": "doc"
				}
			]
		},
		{
			"tool_access_type_id": "QfO:Web-application",
			"link": "http://omabrowser.org/oma/landOMA/"
		},
		{
			"tool_access_type_id": "QfO:Database",
			"link": "http://omabrowser.org/oma/current/"
		}
	]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/QfO_complete_data/QfO_tool_PANTHER-all.json
{
	"_id": "QfO:PANTHER-all",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"bioTools_id": "https://bio.tools/tool/panther/version/1",
	"name": "PANTHER 8.0 (all)",
	"description": "The PANTHER (Protein ANalysis THrough Evolutionary Relationships) Classification System was designed to classify proteins (and their genes) in order to facilitate high-throughput analysis. PANTHER ALL will return all orthologs if more than one",
	"is_automated": true,
	"community_id": ["QfO:QfO"],
	"tool_contact_id": [
		"Paul.Thomas"
	],
	"status_id": "QfO:active",
	"references": [
		"10.1093/nar/gkw1138",
		"10.1093/nar/gkv1194",
		"10.1093/nar/gkp1019",
		"10.1093/nar/gks1118",
		"10.1038/nprot.2013.092",
		"10.1093/nar/gkl869",
		"https://www.ncbi.nlm.nih.gov/pubmed/12520017",
		"10.1093/nar/gki078",
		"10.1101/gr.772403"
	],
	"tool_access": [
		{
			"tool_access_type_id": "QfO:RESTful-Web-API",
			"link": "http://pantherdb.org/help/PANTHERhelp.jsp#V."
		}
	]
}
