=== inab/benchmarking-data-model/json-schemas/0.3.x/tool.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Tool concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the tool. It should be something meaningful, like the tool name, its uri or an acronym",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool" ]
		},
		"bioTools_id": {
			"title": "The unique id of the tool in EXCELERATE WP1 bio.tools registry",
			"type": "string",
			"format": "uri"
		},
		"name": {
			"title": "Short tool name",
			"minLength": 1,
			"type": "string"
		},
		"description": {
			"title": "Long tool name or description",
			"type": "string"
		},
		"is_automated": {
			"title": "Can this tool be automatically invoked?",
			"type": "boolean"
		},
		"community_id": {
			"title": "The community id(s) where this tool belongs",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"tool_contact_id": {
			"title": "The tool's contact id(s)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Contact",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"status_id": {
			"title": "_id of the current tool status",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "ToolStatus",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"references": {
			"title": "The tool's reference id(s)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Reference",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"tool_access": {
			"title": "Methods to access the tool",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "object",
				"properties": {
					"tool_access_type_id": {
						"title": "The tool access type id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "ToolAccessType",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"link": {
						"title": "The base link to the access point (when it is not a local algorithm)",
						"type": "string",
						"format": "uri"
					},
					"techdocs": {
						"title": "Optional technical documentation of the tool access",
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"uri": {
									"title": "The URI of the technical documentation",
									"type": "string",
									"format": "uri"
								},
								"label": {
									"title": "The type of URI (WSDL, WADL, OpenAPI/Swagger, Source code, Miscellaneous documentation)",
									"type": "string",
									"enum": ["WSDL","WADL","OpenAPI","API","source","doc"]
								}
							},
							"additionalProperties": false,
							"required": [
								"uri",
								"label"
							]
						}
					}
				},
				"additionalProperties": true,
				"required": [
					"tool_access_type_id"
				]
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","name","is_automated","community_id","tool_contact_id","status_id","tool_access"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/CAPRI_prototype_data/capri_tool_firedock.json
{
    "_id": "FireDock",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
    "bioTools_id": "FireDock",
    "name": "FireDock",
    "description": "The FireDock web server performs high-throughput flexible refinement and scoring of protein-protein docking solutions. Side chain conformations and rigid body orientations are optimized, and outputs viewed in three-dimensional space.",
    "is_automated": false,
    "community_id":
      [
        "CAPRI"
      ],
    "tool_contact_id": [
      "Haim.J.Wolfson"
    ],
    "status_id": "active",
    "references": [
      "10.1093/nar/gkn186"
    ],
    "tool_access":
      [
        {
          "tool_access_type_id":"Web/API",
          "link":"http://bioinfo3d.cs.tau.ac.il/FireDock/"
        }
      ]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/Biocreative-prototype-data/BioCreative_tool_LingPipe.json
{
	"_id": "BioCreative:LingPipe",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"name": "LingPipe",
	"description": "LingPipe is a suite of NLP tools (in Java) including many features such as named-entity detector, an approximate dictionary match named-entity detector, a heuristic sentence boundary detector, a heuristic within-document coreference resolution engine and a set of tools for MEDLINE data.",
	"is_automated": false,
	"community_id": ["BioCreative"],
	"tool_contact_id": [
		"lingpipe.helpdesk"
	],
	"status_id": "implemented",
	"references": [
		"10.1093/bioinformatics/16.2.169"
	],
	"tool_access": [
		{
			"tool_access_type_id": "Standalone-application",
			"link": "http://alias-i.com/lingpipe/web/downloadJarOrDistro.html?",
			"techdocs": [
				{
					"uri": "http://alias-i.com/lingpipe/web/models.html",
					"label": "source"
				},
				{
					"uri": "http://alias-i.com/lingpipe/demos/tutorial/read-me.html",
					"label": "doc"
				},
				{
					"uri": "http://alias-i.com/lingpipe/web/install.html",
					"label": "doc"
				},
				{
					"uri": "http://alias-i.com/lingpipe/docs/api/index.html",
					"label": "OpenAPI"
				}
			]
		}
	]
}

=== inab/benchmarking-data-model/prototype-data/CAPRI_prototype_data/capri_tool_rosettadock_server.json
{
    "_id": "rosettadock_server",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
    "bioTools_id": "rosettadock_server",
    "name": "RosettaDock Server",
    "description": "Structure prediction program that searches the rigid body and side chain conformational space of two interacting proteins to find a minimum free-energy complex for the protein-protein interaction structure.",
    "is_automated": true,
    "community_id":
      [
        "CAPRI" 
      ],
    "tool_contact_id": [
      "Jeffrey.Gray"
    ],
    "status_id": "active",
    "references": [
      "10.1093/nar/gkn216"
    ],
    "tool_access": 
      [
        {
          "tool_access_type_id":"Web/API",
          "link":"http://rosie.graylab.jhu.edu/"
        }
      ]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/Biocreative-prototype-data/BioCreative_tool_AcroTagger.json
{
	"_id": "BioCreative: AcroTagger",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"name": "AcroTagger",
	"description": "Tool to tag biomedical abbreviations in text using XML.",
	"is_automated": false,
	"community_id": ["BioCreative"],
	"tool_contact_id": [
		"Sylvain.Gaudan"
	],
	"status_id": "active",
	"references": [
		"10.1093/bioinformatics/bti586"
	],
	"tool_access": [
		{
			"tool_access_type_id": "Database",
			"link": "ftp://ftp.ebi.ac.uk/pub/software/textmining/abbreviation_resolution/"
		}
	]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/Biocreative-prototype-data/BioCreative_tool_T2KGeneTagger.json
{
	"_id": "BioCreative:T2KGeneTagger",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"name": "T2K Gene Tagger",
	"description": "T2K Gene Tagger is a web tool that take a medical text file or a list of gene names and tag genes with <'gene'> tag with taxonomy and sequence information. Note that it will take quiet a long time if you are tagging a long paragraphs or a full paper.",
	"is_automated": false,
	"community_id": ["BioCreative"],
	"tool_contact_id": [
		"Yong.Huang"
	],
	"status_id": "active",
	"tool_access": [
		{
			"tool_access_type_id": "Web-application",
			"link": "http://www.bioinformatics.org/textknowledge/genetag.php"		}
	]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/CAPRI_prototype_data/capri_tool_cluspro.json
{
    "_id": "ClusPro",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
    "bioTools_id": "ClusPro",
    "name": "ClusPro",
    "description": "ClusPro is a tool for automatically computing the docking of two protein structures supplied by the user (or as PDB IDs). The result set is a ranked list of putative complexes, ordered by clustering properties.",
    "is_automated": true,
    "community_id":
      [
        "CAPRI"
      ],
    "tool_contact_id": [
      "Sandor.Vajda"
    ],
    "status_id": "active",
    "references": [
      "10.1093/nar/gkh354",
      "10.1002/prot.22835",
      "10.1002/prot.21117"
    ],
    "tool_access":
      [
        {
          "tool_access_type_id":"Web/API",
          "link":"http://cluspro.bu.edu/login.php"
        }
      ]
}

=== inab/benchmarking-data-model/prototype-data/CAPRI_prototype_data/capri_tool_symmdock.json
{
    "_id": "SymmDock",
    "_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
    "bioTools_id": "SymmDock",
    "name": "SymmDock",
    "description": "SymmDock is an server for prediction of complexes with cyclically symmetry by geometry based molecular docking.",
    "is_automated": true,
    "community_id":
      [
        "CAPRI" 
      ],
    "tool_contact_id": [
      "Dina.Schneidman-Duhovny"
    ],
    "status_id": "active",
    "references": [
      "10.1093/nar/gki481"
    ],
    "tool_access": 
      [
        {
          "tool_access_type_id":"Web/API",
          "link":"http://bioinfo3d.cs.tau.ac.il/SymmDock/"
        }
      ]
}

=== inab/benchmarking-data-model/prototype-data/0.3.x/Biocreative-prototype-data/BioCreative_tool_MaxMatcher.json
{
	"_id": "BioCreative:MaxMatcher",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Tool",
	"name": "MaxMatcher",
	"description": "MaxMatcher is a biological concept extractor tool using dicitonary-based approximate matching. UMLS 2004AA version is used as the dictionary. The precision and recall on GENIA3.02 corpus are 71.60% and 75.18%, respectively.",
	"is_automated": false,
	"community_id": ["BioCreative"],
	"tool_contact_id": [
		"Xiaohua.Zhou"
	],
	"status_id": "implemented",
	"references": [
		"10.1109/ICTAI.2007.117",
		"10.1007/978-3-540-36668-3_150"
	],
	"tool_access": [
		{
			"tool_access_type_id": "Standalone-application",
			"link": "http://dragon.ischool.drexel.edu/example/maxmatcher.zip"
		}
	]
}
