=== inab/benchmarking-data-model/json-schemas/0.4.x/reference.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.4/Reference",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Bibliographic reference concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the bibliographic reference. It should be something meaningful, like its DOI or its PubMedId",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.4/Reference" ]
		},
		"title": {
			"title": "The title of the referenced material",
			"type": "string"
		},
		"bibliographic_ids": {
			"title": "The recorded bibliographic ids of the referenced material, as CURIE/identifiers.org format or a bare link",
			"type": "array",
			"minLength": 1,
			"items": {
				"title": "Currently, the accepted ids are pmid, doi and pmc",
				"type": "string",
				"format": "uri",
				"pattern": "^(pmid|doi|pmc|isbn|issn|http(s)?):.+$"
			}
		},
		"abstract": {
			"title": "Optionally, the abstract of the referenced material",
			"type": "string"
		},
		"links": {
			"title": "Optional links related to the bibliographic reference",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"title": "The URI of the link related to the bibliographic reference",
						"type": "string",
						"format": "uri"
					},
					"label": {
						"title": "The type of URI",
						"type": "string",
						"enum": ["PublicationDOI","LinkedInGroup","MainSite","DataSite"]
					}
				},
				"additionalProperties": false,
				"required": [
					"uri",
					"label"
				]
			}
		},
		"authors": {
			"title": "Optional list of authors of the referenced material",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"givenName": {
						"title": "First / given name (or initials)",
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "string",
							"minLength": 1
						}
					},
					"surname": {
						"title": "Surname(s)",
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "string",
							"minLength": 1
						}
					},
					"contact_id": {
						"title": "If it is a known contact, its contact id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Contact",
								"members": [ "." ]
							}
						],
						"minLength": 1
					}
				},
				"additionalProperties": false,
				"required": [
					"givenName",
					"surname"
				]
			}
		}
	},
	"additionalProperties": true,
	"required": ["_id","_schema","title","bibliographic_ids"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/0.4.x/QfO_v0.4/References/QfO_reference41.json
{
	"_id": "10.1093/bioinformatics/btm295",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.4/Reference",
	"title": "OMA Browserâ€”Exploring orthologous relations across 352 complete genomes",
	"bibliographic_ids":["http://dx.doi.org/10.1093/bioinformatics/btm295"],
	"abstract": "Motivation: Inference of the evolutionary relation between proteins, in particular the identification of orthologs, is a central problem in comparative genomics. Several large-scale efforts with various methodologies and scope tackle this problem, including OMA (the Orthologous MAtrix project). Results: Based on the results of the OMA project, we introduce here the OMA Browser, a web-based tool allowing the exploration of orthologous relations over 352 complete genomes. Orthologs can be viewed as groups across species, but also at the level of sequence pairs, allowing the distinction among one-to-one, one-to-many and many-to-many orthologs. Availability:http://omabrowser.org"
}
